Repository thrasher-corp/gocryptotrader, pull requests merged in 2019-09, with the labels that each got.

#347 (Engine) Logger - fixes issues with multiwriter go routine
  logger/logger.go
  logger/logger_multiwriter.go
  logger/logger_rotate.go
  logger/logger_setup.go
  logger/logger_types.go
  logger/loggers.go
  logger/sublogger_types.go
Labels: bug

#352 (Engine) Gate-IO Websocket subscription pairs case sensitivity
  exchanges/gateio/gateio_websocket.go
Labels: bug

#353 Exchange wrapper test tool
  cmd/exchange_wrapper_issues/.gitignore
  cmd/exchange_wrapper_issues/main.go
  cmd/exchange_wrapper_issues/report.tmpl
  cmd/exchange_wrapper_issues/types.go
  cmd/exchange_wrapper_issues/wrapperconfig.json
Labels: Review Me

#363 Config overwrite bug
  cmd/dbmigrate/main.go
  cmd/exchange_template/exchange_template.go
  cmd/gen_otp/otp_gen.go
  cmd/portfolio/portfolio.go
  cmd/websocket_client/main.go
  communications/slack/slack_test.go
  communications/smsglobal/smsglobal_test.go
  communications/smtpservice/smtpservice_test.go
  communications/telegram/telegram_test.go
  config/config.go
  config/config_encryption.go
  config/config_encryption_test.go
  config/config_test.go
  engine/engine.go
  engine/exchange_test.go
  engine/helpers_test.go
  engine/restful_server.go
  engine/restful_server_test.go
  engine/syncer_test.go
  engine/websocket.go
  exchanges/anx/anx_live_test.go
  exchanges/anx/anx_mock_test.go
  exchanges/binance/binance_live_test.go
  exchanges/binance/binance_mock_test.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitflyer/bitflyer_test.go
  exchanges/bithumb/bithumb_test.go
  exchanges/bitmex/bitmex_test.go
  exchanges/bitstamp/bitstamp_live_test.go
  exchanges/bitstamp/bitstamp_mock_test.go
  exchanges/bittrex/bittrex_test.go
  exchanges/btcmarkets/btcmarkets_test.go
  exchanges/btse/btse_test.go
  exchanges/coinbasepro/coinbasepro_test.go
  exchanges/coinut/coinut_test.go
  exchanges/exchange_test.go
  exchanges/exmo/exmo_test.go
  exchanges/gateio/gateio_test.go
  exchanges/gemini/gemini_live_test.go
  exchanges/gemini/gemini_mock_test.go
  exchanges/hitbtc/hitbtc_test.go
  exchanges/huobi/huobi_test.go
  exchanges/itbit/itbit_test.go
  exchanges/kraken/kraken_test.go
  exchanges/lakebtc/lakebtc_test.go
  exchanges/lbank/lbank_test.go
  exchanges/localbitcoins/localbitcoins_live_test.go
  exchanges/localbitcoins/localbitcoins_mock_test.go
  exchanges/okcoin/okcoin_test.go
  exchanges/okex/okex_test.go
  exchanges/poloniex/poloniex_live_test.go
  exchanges/poloniex/poloniex_mock_test.go
  exchanges/yobit/yobit_test.go
  exchanges/zb/zb_test.go
  main.go
Labels: Review Me, bug
