Repository thrasher-corp/gocryptotrader, pull requests merged in 2020-02, with the labels that each got.

#433 Huobi: Add deposit address and withdraw quota API support
  exchanges/huobi/huobi.go
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_types.go
  exchanges/huobi/huobi_wrapper.go
  go.mod
  go.sum
Labels: enhancement, review me

#438 Engine: SyncTimeout can't be set
  engine/engine.go
Labels: bug

#443 Minor general cleanup and bug fixes
  cmd/huobi_auth/main.go
  cmd/portfolio/portfolio.go
  config/config.go
  config/config_test.go
  config/config_types.go
  config_example.json
  engine/engine.go
  engine/rpcserver.go
  exchanges/coinbene/coinbene.go
  exchanges/huobi/huobi.go
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_wrapper.go
  go.sum
  testdata/configtest.json
Labels: enhancement, review me

#447 (QOL) Improve test setup for logger, improve test coverage for database
  database/repository/audit/audit_test.go
  database/repository/script/script_test.go
  database/testhelpers/test_helpers.go
  database/testhelpers/test_helpers_test.go
  database/tests/database_test.go
  log/logger_test.go
Labels: enhancement, review me

#441 fix 440: SubmitOrder and CB-ACCESS-TIMESTAMP value
  .gitignore
  exchanges/coinbasepro/coinbasepro.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
Labels: bug, review me

#456 Coinut: Fix nonce issue based on new API change
  exchanges/coinut/coinut.go
  exchanges/coinut/coinut_test.go
  exchanges/coinut/coinut_websocket.go
  exchanges/coinut/coinut_wrapper.go
Labels: review me
