Repository thrasher-corp/gocryptotrader, pull requests merged in 2020-03, with the labels that each got.

#458 Bitfinex: Implement leaderboard API
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
Labels: review me

#453 Implementation of Exchange GetOrder through GRPC for Coinbase
  engine/rpcserver.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/order/order_types.go
  exchanges/order/orders.go
  gctrpc/rpc.pb.go
  gctrpc/rpc.proto
  gctrpc/rpc.swagger.json
Labels: review me

#468 (BUG FIX) Fix order submission crash due to missing "exchange" parameter
  engine/rpcserver.go
Labels: bug, review me

#472 (BTC Markets) Add support for GetHistoricCandles wrapper
  config/config.go
  exchanges/btcmarkets/btcmarkets.go
  exchanges/btcmarkets/btcmarkets_test.go
  exchanges/btcmarkets/btcmarkets_types.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  log/logger_types.go
  log/loggers.go
Labels: enhancement, review me

#474 (FIX) Update ZB API URLs
  exchanges/zb/zb.go
  exchanges/zb/zb_test.go
  exchanges/zb/zb_websocket.go
Labels: review me

#475 (BUGFIX) OKCoin websocket port update
  exchanges/okcoin/okcoin.go
Labels: bug, review me
