Repository thrasher-corp/gocryptotrader, pull requests merged in 2020-09, with the labels that each got.

#550 BUGFIX: PSQL Migration syntax fix
  database/migrations/20200814113829_update_withdrawal_history_add_not_null_to_exchange_name_id/postgres.sql
  database/migrations/20200814121412_update_candle_add_not_null_to_asset/postgres.sql
Labels: bug, review me

#557 Codecov: Add config plus disable annotations for PRs
  codecov.yml
Labels: review me

#549 Config/Engine: Add data directory to config.json
  config/config.go
  config/config_test.go
  config/config_types.go
  config_example.json
  engine/engine.go
  engine/engine_test.go
Labels: enhancement, review me

#560 Engine: Remove incorrect creation of data directory
  engine/engine.go
Labels: bug, review me

#563 Engine: Refactor use of global Bot
  cmd/config_builder/builder.go
  cmd/exchange_wrapper_coverage/main.go
  cmd/exchange_wrapper_issues/main.go
  currency/storage.go
  engine/addr_helpers.go
  engine/connection.go
  engine/engine.go
  engine/engine_test.go
  engine/exchange.go
  engine/exchange_test.go
  engine/fake_exchange_test.go
  engine/helpers.go
  engine/helpers_test.go
  engine/orders.go
  engine/portfolio.go
  engine/restful_router.go
  engine/restful_server.go
  engine/restful_server_test.go
  engine/routines.go
  engine/rpcserver.go
  engine/syncer.go
  engine/syncer_test.go
  engine/websocket.go
  engine/withdraw.go
  gctscript/wrappers/gct/exchange/exchange.go
  gctscript/wrappers/gct/exchange/exchange_test.go
Labels: review me

#566 Config: Remove TestBypass flag
  cmd/dbseed/dbseed_test.go
  config/config.go
  config/config_test.go
  config/config_types.go
Labels: review me
