Repository thrasher-corp/gocryptotrader, pull requests merged in 2020-10, with the labels that each got.

#571 Config: do to not store decryption variables globally
  config/config.go
  config/config_encryption.go
  config/config_encryption_test.go
  config/config_types.go
Labels: review me

#575 Config: fix don't create empty dir when resolving path
  common/file/file.go
  common/file/file_test.go
  config/config.go
  config/config_test.go
  engine/engine.go
  engine/engine_test.go
  engine/exchange.go
  engine/exchange_test.go
  gctscript/wrappers/gct/exchange/exchange_test.go
  main.go
Labels: review me

#579 Bug fix in RoundFloat func in common/math package
  common/math/math.go
  common/math/math_test.go
  go.sum
Labels: review me

#581 Asset package update
  cmd/exchange_wrapper_issues/main.go
  cmd/gctcli/validation.go
  config/config.go
  engine/rpcserver.go
  engine/websocket.go
  exchanges/asset/asset.go
  exchanges/asset/asset_test.go
  gctscript/modules/gct/exchange.go
Labels: bug, enhancement, review me

#572 Getting closed orders implementation, fixed Binance MARKET order creation, expanded SubmitOrder response
  cmd/exchange_template/wrapper_file.tmpl
  cmd/exchange_wrapper_coverage/main.go
  cmd/exchange_wrapper_issues/main.go
  cmd/gctcli/commands.go
  engine/fake_exchange_test.go
  engine/rpcserver.go
  exchanges/alphapoint/alphapoint_wrapper.go
  exchanges/binance/binance.go
  exchanges/binance/binance_types.go
  exchanges/binance/binance_wrapper.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bitflyer/bitflyer_wrapper.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/bittrex/bittrex_wrapper.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/btse/btse_wrapper.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinbene/coinbene_wrapper.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/exmo/exmo_wrapper.go
  exchanges/ftx/ftx_wrapper.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gemini/gemini_wrapper.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/interfaces.go
  exchanges/itbit/itbit_wrapper.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/lakebtc/lakebtc_wrapper.go
  exchanges/lbank/lbank_test.go
  exchanges/lbank/lbank_wrapper.go
  exchanges/localbitcoins/localbitcoins_wrapper.go
  exchanges/okgroup/okgroup_wrapper.go
  exchanges/order/order_types.go
  exchanges/order/orders.go
  exchanges/poloniex/poloniex_wrapper.go
  exchanges/yobit/yobit_test.go
  exchanges/yobit/yobit_wrapper.go
  exchanges/zb/zb_wrapper.go
  gctrpc/rpc.pb.go
  gctrpc/rpc.pb.gw.go
  gctrpc/rpc.proto
  gctrpc/rpc.swagger.json
  gctscript/examples/exchange/query_order.gct
  gctscript/modules/gct/exchange.go
  gctscript/modules/wrapper_types.go
  gctscript/wrappers/gct/exchange/exchange.go
  gctscript/wrappers/gct/exchange/exchange_test.go
  gctscript/wrappers/validator/validator.go
  gctscript/wrappers/validator/validator_test.go
Labels: review me

#583 FTX: Fix order placement/cancellation issues
  exchanges/ftx/ftx.go
  exchanges/ftx/ftx_test.go
  exchanges/ftx/ftx_wrapper.go
Labels: review me

#582 Exchanges: Include format pair in wrapper functions and test for formatting issues via tool wrapper issues
  cmd/exchange_wrapper_issues/exchange_wrapper_issues_test.go
  cmd/exchange_wrapper_issues/main.go
  cmd/exchange_wrapper_issues/wrapperconfig.json
  cmd/gctcli/commands.go
  currency/code.go
  currency/pair_test.go
  exchanges/alphapoint/alphapoint_wrapper.go
  exchanges/binance/binance.go
  exchanges/binance/binance_wrapper.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bitflyer/bitflyer_wrapper.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/bittrex/bittrex_wrapper.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/exmo/exmo_wrapper.go
  exchanges/ftx/ftx_wrapper.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gemini/gemini_wrapper.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/itbit/itbit_wrapper.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/lakebtc/lakebtc_wrapper.go
  exchanges/localbitcoins/localbitcoins_wrapper.go
  exchanges/okex/okex_wrapper.go
  exchanges/okgroup/okgroup_wrapper.go
  exchanges/poloniex/poloniex_wrapper.go
  exchanges/yobit/yobit_wrapper.go
  exchanges/zb/zb_wrapper.go
Labels: bug, review me
