Repository thrasher-corp/gocryptotrader, pull requests merged in 2020-01, with the labels that each got.

#411 (COMMON/FILE) Add Zip create/extract support
  common/file/archive/zip.go
  common/file/archive/zip_test.go
  testdata/testdata.zip
  testdata/zip-slip.zip
Labels: enhancement, review me

#412 Engine: Use atomic.LoadInt32/AddInt32 for starting/stopping the database subsystem
  cmd/dbmigrate/main.go
  engine/database.go
Labels: bug, review me

#415 Bugfix: Introduces a new config.DefaultFilePath func
  cmd/config/config.go
  cmd/dbmigrate/main.go
  cmd/gen_otp/otp_gen.go
  cmd/gen_sqlboiler_config/main.go
  cmd/portfolio/portfolio.go
  config/config.go
  config/config_test.go
  main.go
Labels: review me

#418 LintFix: Bittrex properties and tests
  exchanges/bittrex/bittrex_test.go
  exchanges/bittrex/bittrex_types.go
Labels: review me

#419 Bittrex - changed type of field "Id" in DepositHistory struct
  engine/helpers.go
  exchanges/bittrex/bittrex_types.go
Labels: review me

#420 (COMMON): Basic (Least Recently Used) LRU caching system
  common/cache/README.md
  common/cache/cache.go
  common/cache/cache_test.go
  common/cache/cache_types.go
  common/cache/lru.go
Labels: enhancement, review me

#414 Add OHLC retrieval func (GetHistoricCandles) to all exchanges and expose it as a wrapper func
  cmd/gctcli/commands.go
  cmd/gctcli/main.go
  common/common.go
  common/common_test.go
  engine/rpcserver.go
  exchanges/binance/binance.go
  exchanges/bitfinex/bitfinex.go
  exchanges/bitflyer/bitflyer.go
  exchanges/bithumb/bithumb.go
  exchanges/bitmex/bitmex.go
  exchanges/bitstamp/bitstamp.go
  exchanges/bittrex/bittrex.go
  exchanges/btcmarkets/btcmarkets.go
  exchanges/btse/btse.go
  exchanges/coinbasepro/coinbasepro.go
  exchanges/coinbasepro/coinbasepro_test.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinbene/coinbene.go
  exchanges/coinut/coinut.go
  exchanges/exchange_types.go
  exchanges/exmo/exmo.go
  exchanges/gateio/gateio.go
  exchanges/gemini/gemini.go
  exchanges/hitbtc/hitbtc.go
  exchanges/huobi/huobi.go
  exchanges/interfaces.go
  exchanges/itbit/itbit.go
  exchanges/kraken/kraken.go
  exchanges/lakebtc/lakebtc.go
  exchanges/lbank/lbank.go
  exchanges/localbitcoins/localbitcoins.go
  exchanges/okcoin/okcoin.go
  exchanges/okex/okex.go
  exchanges/poloniex/poloniex.go
  exchanges/protocol/features.go
  exchanges/yobit/yobit.go
  exchanges/zb/zb.go
  gctrpc/gen_pb_linux.sh
  gctrpc/rpc.pb.go
  gctrpc/rpc.pb.gw.go
  gctrpc/rpc.proto
  gctrpc/rpc.swagger.json
Labels: enhancement, review me

#421 GCTCLI: Destination var/arg check usage fixes
  cmd/gctcli/commands.go
  exchanges/binance/binance.go
  exchanges/bitfinex/bitfinex.go
  exchanges/bitflyer/bitflyer.go
  exchanges/bithumb/bithumb.go
  exchanges/bitmex/bitmex.go
  exchanges/bitstamp/bitstamp.go
  exchanges/bittrex/bittrex.go
  exchanges/btcmarkets/btcmarkets.go
  exchanges/btse/btse.go
  exchanges/coinbene/coinbene.go
  exchanges/coinut/coinut.go
  exchanges/exmo/exmo.go
  exchanges/gateio/gateio.go
  exchanges/gemini/gemini.go
  exchanges/hitbtc/hitbtc.go
  exchanges/huobi/huobi.go
  exchanges/itbit/itbit.go
  exchanges/kraken/kraken.go
  exchanges/lakebtc/lakebtc.go
  exchanges/lbank/lbank.go
  exchanges/localbitcoins/localbitcoins.go
  exchanges/okcoin/okcoin.go
  exchanges/okex/okex.go
  exchanges/poloniex/poloniex.go
  exchanges/withdraw/withdraw_types.go
  exchanges/yobit/yobit.go
  exchanges/zb/zb.go
Labels: review me

#432 (PROFILING): Add config support for setting runtime.SetMutexProfileFraction() value
  config/config_types.go
  config_example.json
  engine/restful_router.go
  engine/restful_server_test.go
  testdata/configtest.json
Labels: enhancement, review me
