Repository thrasher-corp/gocryptotrader, pull requests merged in 2022-09, with the labels that each got.

#1022 Binance: add IOC support to SubmitOrder wrapper
  exchanges/binance/binance_wrapper.go
Labels: review me

#991 exchange: upgrade UpdatePair method
  backtester/engine/setup.go
  backtester/eventhandlers/strategies/ftxcashandcarry/ftxcashandcarry.go
  backtester/report/chart.go
  cmd/exchange_template/exchange_template.go
  cmd/exchange_wrapper_issues/main.go
  config/config.go
  config/config_test.go
  currency/currency_types.go
  currency/manager.go
  currency/manager_test.go
  currency/pair.go
  currency/pair_methods.go
  currency/pair_test.go
  currency/pair_types.go
  currency/pairs.go
  currency/pairs_test.go
  engine/engine.go
  engine/helpers_test.go
  engine/rpcserver.go
  engine/rpcserver_test.go
  engine/sync_manager.go
  engine/sync_manager_test.go
  engine/sync_manager_types.go
  engine/websocketroutine_manager.go
  engine/websocketroutine_manager_test.go
  exchanges/binance/binance_wrapper.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bithumb/bithumb_test.go
  exchanges/bithumb/bithumb_websocket.go
  exchanges/bithumb/bithumb_websocket_test.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex.go
  exchanges/bitmex/bitmex_types.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/btse/btse_wrapper.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/bybit/bybit_ws_futures.go
  exchanges/bybit/bybit_ws_ufutures.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/ftx/ftx_test.go
  exchanges/ftx/ftx_wrapper.go
  exchanges/hitbtc/hitbtc_test.go
  exchanges/huobi/huobi_futures.go
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/itbit/itbit_wrapper.go
  exchanges/localbitcoins/localbitcoins_wrapper.go
  exchanges/okcoin/okcoin_test.go
  exchanges/okex/okex_test.go
  exchanges/okex/okex_wrapper.go
  exchanges/stream/buffer/buffer_test.go
  exchanges/zb/zb_wrapper.go
Labels: bug, review me

#1025 coinbase/kraken: Add IOC support to SubmitOrder wrappers
  exchanges/coinbasepro/coinbasepro.go
  exchanges/coinbasepro/coinbasepro_types.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
Labels: review me

#1031 websocket: add SendMessageReturnResponse latency reporter
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
Labels: review me

#1043 binance/perf: Optimize UFuturesNewOrder function parameters
  exchanges/binance/binance_test.go
  exchanges/binance/binance_ufutures.go
  exchanges/binance/binance_wrapper.go
  exchanges/binance/ufutures_types.go
Labels: reconstructing

#1041 engine: fix potential difference between exchange config name and default
  engine/engine.go
  engine/sync_manager.go
  engine/sync_manager_test.go
Labels: review me

#1044 ftx: Add support for hidden referral API endpoints
  exchanges/ftx/ftx.go
  exchanges/ftx/ftx_test.go
  exchanges/ftx/ftx_types.go
Labels: review me

#1049 ftx: fix null currency.Pair UnmarshalJSON
  currency/pair_methods.go
  currency/pair_test.go
Labels: review me

#1040 backtester: run manager
  backtester/btcli/commands.go
  backtester/btcli/main.go
  backtester/btrpc/btrpc.pb.go
  backtester/btrpc/btrpc.pb.gw.go
  backtester/btrpc/btrpc.proto
  backtester/btrpc/btrpc.swagger.json
  backtester/btrpc/btrpc_grpc.pb.go
  backtester/engine/backtest.go
  backtester/engine/backtest_test.go
  backtester/engine/backtest_types.go
  backtester/engine/grpcserver.go
  backtester/engine/grpcserver_test.go
  backtester/engine/runmanager.go
  backtester/engine/runmanager_test.go
  backtester/engine/setup.go
  backtester/engine/setup_test.go
  backtester/eventhandlers/statistics/statistics.go
  backtester/eventhandlers/statistics/statistics_types.go
  backtester/main.go
  backtester/report/report.go
  common/timeperiods/timeperiods.go
  exchanges/binance/binance.go
  exchanges/binanceus/binanceus.go
  exchanges/kline/kline.go
  log/logger_multiwriter.go
Labels: review me
