Repository thrasher-corp/gocryptotrader, pull requests merged in 2023-10, with the labels that each got.

#1335 Okx: Various websocket fixes
  exchanges/okx/okx.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
Labels: review me, szrc

#1359 spellcheck: fix and update
  cmd/documentation/currency_templates/fx_currencyconverterapi.tmpl
  cmd/documentation/currency_templates/fx_currencylayer.tmpl
  cmd/documentation/currency_templates/fx_exchangeratehost.tmpl
  cmd/documentation/currency_templates/fx_exchangeratesapi.tmpl
  cmd/documentation/currency_templates/fx_fixer.tmpl
  cmd/documentation/currency_templates/fx_openexchangerates.tmpl
  config/config.go
  contrib/spellcheck/exclude_lines.txt
  currency/forexprovider/currencyconverterapi/README.md
  currency/forexprovider/currencylayer/README.md
  currency/forexprovider/exchangerate.host/README.md
  currency/forexprovider/exchangeratesapi.io/README.md
  currency/forexprovider/fixer.io/README.md
  currency/forexprovider/openexchangerates/README.md
  currency/storage_types.go
  exchanges/binance/binance_websocket.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/bithumb/bithumb_ws_orderbook.go
  exchanges/bitmex/bitmex.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/coinut/coinut_websocket.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gemini/gemini_types.go
  exchanges/huobi/huobi_types.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/okcoin/okcoin_errors_map.go
  exchanges/orderbook/linked_list.go
  exchanges/stream/websocket_connection.go
  exchanges/yobit/yobit_types.go
Labels: review me

#1357 orderbook: fix race condition when function scope is in error.
  exchanges/orderbook/depth.go
Labels: review me

#1349 maps: expansion of Key concept
  backtester/data/data.go
  backtester/data/data_test.go
  backtester/data/data_types.go
  backtester/engine/backtest.go
  backtester/engine/backtest_test.go
  backtester/engine/setup.go
  backtester/eventhandlers/portfolio/portfolio.go
  backtester/eventhandlers/portfolio/portfolio_test.go
  backtester/eventhandlers/portfolio/portfolio_types.go
  backtester/eventhandlers/portfolio/risk/risk.go
  backtester/eventhandlers/portfolio/risk/risk_test.go
  backtester/eventhandlers/portfolio/risk/risk_types.go
  backtester/eventhandlers/portfolio/setup.go
  backtester/eventhandlers/statistics/currencystatistics.go
  backtester/eventhandlers/statistics/currencystatistics_test.go
  backtester/eventhandlers/statistics/fundingstatistics.go
  backtester/eventhandlers/statistics/fundingstatistics_test.go
  backtester/eventhandlers/statistics/printresults.go
  backtester/eventhandlers/statistics/statistics.go
  backtester/eventhandlers/statistics/statistics_test.go
  backtester/eventhandlers/statistics/statistics_types.go
  backtester/report/chart.go
  backtester/report/chart_test.go
  backtester/report/report.go
  backtester/report/report_test.go
  backtester/report/tpl.gohtml
  common/key/key.go
  common/key/key_test.go
  engine/engine_test.go
  engine/event_manager_test.go
  exchanges/account/account.go
  exchanges/account/account_test.go
  exchanges/account/account_types.go
  exchanges/asset/asset.go
  exchanges/bithumb/bithumb_test.go
  exchanges/exchange.go
  exchanges/futures/futures.go
  exchanges/futures/futures_test.go
  exchanges/futures/futures_types.go
  exchanges/orderbook/linked_list_test.go
  exchanges/orderbook/orderbook.go
  exchanges/orderbook/orderbook_types.go
  exchanges/stream/buffer/buffer.go
  exchanges/stream/buffer/buffer_test.go
  exchanges/stream/buffer/buffer_types.go
  exchanges/ticker/ticker.go
  exchanges/ticker/ticker_types.go
Labels: review me, rebase/merge of master required

#1243 engine: Adds new helper functions for default exchange deployment.
  engine/exchange_manager.go
  engine/helpers.go
  engine/helpers_test.go
Labels: review me

#1333 Bitstamp: Add auth channel subscription handling
  currency/manager.go
  currency/manager_test.go
  currency/manager_types.go
  exchanges/bitstamp/bitstamp.go
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_type_convert.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/bitstamp/testdata/wsMyOrders.json
  exchanges/kraken/kraken_test.go
  exchanges/sharedtestvalues/sharedtestvalues.go
  testdata/http_mock/bitstamp/bitstamp.json
Labels: review me, szrc

#1336 OrderManager: Fix race condition in submit with ws
  engine/order_manager.go
  engine/order_manager_test.go
  exchanges/bitfinex/bitfinex_test.go
Labels: review me, szrc

#1356 Bitfinex: Fix websocket panic when seqNo is not sent
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
  exchanges/bitfinex/bitfinex_websocket.go
Labels: bug, review me, gcrc, szrc

#1360 exchange: refactor credentials.go from #1320
  exchanges/credentials.go
  exchanges/credentials_test.go
  exchanges/exchange.go
  exchanges/exchange_types.go
Labels: review me, gcrc

#1346 Okx: Websocket order channel fixes
  exchanges/okx/okx_test.go
  exchanges/okx/okx_type_convert.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/okx/testdata/wsOrders.json
  exchanges/order/order_test.go
  exchanges/order/orders.go
  exchanges/sharedtestvalues/sharedtestvalues.go
Labels: review me, gcrc, szrc

#1289 Bitstamp: Add new trading fees API endpoint; refine fee calcuations and test coverage
  exchanges/bitstamp/bitstamp.go
  exchanges/bitstamp/bitstamp_live_test.go
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_types.go
  testdata/http_mock/bitstamp/bitstamp.json
Labels: review me, szrc

#1275 Okx: Integrate websocket book5 processing and add configurable max subscriptions per connection
  engine/websocketroutine_manager.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_type_convert.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
Labels: bug, review me, gcrc

#1354 orderbook: Add optional orderbook.Item string fields for potential checksum calculations
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_websocket.go
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
  exchanges/orderbook/linked_list.go
  exchanges/orderbook/linked_list_test.go
  exchanges/orderbook/orderbook.go
  exchanges/orderbook/orderbook_test.go
  exchanges/orderbook/orderbook_types.go
Labels: review me, gcrc

#1312 currency: Adds matching lookup table built from available pairs.
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  currency/currency_types.go
  currency/manager.go
  currency/manager_test.go
  currency/manager_types.go
  currency/pair.go
  currency/pair_methods.go
  currency/pair_types.go
  currency/pairs.go
  engine/rpcserver.go
  engine/rpcserver_test.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bitmex/bitmex_test.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_type_convert.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/bybit/bybit_ws_cfutures.go
  exchanges/bybit/bybit_ws_futures.go
  exchanges/bybit/bybit_ws_ufutures.go
  exchanges/coinut/coinut_types.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/exmo/exmo_test.go
  exchanges/exmo/exmo_wrapper.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gemini/gemini_types.go
  exchanges/hitbtc/hitbtc_test.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/interfaces.go
  exchanges/okx/okx.go
Labels: review me, gcrc

#1372 kraken: panic fix, lint: fixes, bittrex: batch tickers, gemini: order limits, tradable pairs
  exchanges/bittrex/bittrex.go
  exchanges/bittrex/bittrex_test.go
  exchanges/bittrex/bittrex_types.go
  exchanges/bittrex/bittrex_wrapper.go
  exchanges/gemini/gemini.go
  exchanges/gemini/gemini_test.go
  exchanges/gemini/gemini_types.go
  exchanges/gemini/gemini_wrapper.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/order/order_test.go
  exchanges/stats/stats.go
  exchanges/stats/stats_test.go
  exchanges/stats/stats_types.go
  testdata/http_mock/gemini/gemini.json
Labels: bug, review me, szrc

#1361 engine/syncer: Stop orderbook fallover to REST when websocket connection is active
  engine/sync_manager.go
Labels: review me, gcrc
