Repository thrasher-corp/gocryptotrader, pull requests merged in 2023-06, with the labels that each got.

#1208 telegram: Fix pushing events to an authorised client list
  cmd/documentation/communications_templates/telegram.tmpl
  communications/base/base.go
  communications/telegram/README.md
  communications/telegram/telegram.go
  communications/telegram/telegram_test.go
  config/config.go
  config_example.json
  testdata/configtest.json
Labels: review me

#1210 websocket: Fix redundant connection monitor error upon disconnect
  exchanges/stream/websocket.go
Labels: review me

#1191 Bitfinex: filter security asset type from spot trading pairs
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/orderbook/orderbook.go
  exchanges/orderbook/orderbook_test.go
  go.sum
Labels: review me

#1219 websocket: Check for slice size to avoid panic when classifying empty binary message
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
Labels: bug, review me

#1217 currency: Add OrderParameters helpers for currency pair
  currency/pair_methods.go
  currency/pair_test.go
  currency/pair_types.go
Labels: review me

#1221 OKx: Fix websocket subscriptions and casing
  exchanges/okx/okx.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1193 orders: Fix manager not processing immediately
  engine/order_manager.go
  engine/order_manager_types.go
Labels: review me

#1225 Okx: Fix Instrument unmarshal
  exchanges/okx/okx_test.go
  exchanges/okx/okx_type_convert.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1228 okx: REST orderbook depth fix
  contrib/spellcheck/exclude_lines.txt
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1192 bybit: assortment of updates
  common/convert/convert.go
  common/convert/convert_test.go
  exchanges/binance/binance.go
  exchanges/binance/binance_cfutures.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_ufutures.go
  exchanges/bithumb/bithumb.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/bybit/bybit.go
  exchanges/bybit/bybit_cfutures.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_usdcfutures.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/bybit/bybit_ws_cfutures.go
  exchanges/bybit/bybit_ws_futures.go
  exchanges/bybit/bybit_ws_ufutures.go
  exchanges/bybit/futures_type.go
  exchanges/bybit/ratelimit.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_wrapper.go
  exchanges/order/limits.go
  exchanges/order/limits_test.go
  exchanges/sharedtestvalues/sharedtestvalues.go
  exchanges/ticker/ticker.go
  exchanges/ticker/ticker_test.go
Labels: review me

#1230 currency: Add Pair method IsAssociated
  currency/pair_methods.go
  currency/pair_test.go
  currency/pair_types.go
Labels: low priority, review me

#1227 okx: GetDefaultConfig fix & ticker field improvements
  contrib/spellcheck/exclude_lines.txt
  engine/engine_test.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
Labels: bug, review me

#1235 Orders: Fix ClientOrderID not updated in merge
  exchanges/order/order_test.go
  exchanges/order/orders.go
Labels: review me

#1237 dispatch: channel reuse fix
  dispatch/dispatch.go
  dispatch/dispatch_test.go
  dispatch/dispatch_types.go
  dispatch/mux.go
  engine/rpcserver.go
  exchanges/account/account_test.go
Labels: review me

#1244 okx: Add fee fields for USDC pairs
  exchanges/okx/okx.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
Labels: review me
