Repository thrasher-corp/gocryptotrader, pull requests merged in 2023-05, with the labels that each got.

#1174 OKX: Fix authenticated websocket blocking during login
  exchanges/okx/okx_test.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1176 OKX: Fix GetActiveOrders bug and remove redundant json.Unmarshal call
  exchanges/okx/okx.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1182 BTSE: Filter no liquidity pairs
  exchanges/btse/btse_types.go
  exchanges/btse/btse_wrapper.go
Labels: review me

#1185 poloniex: filter non-liquid and unused assets
  exchanges/lbank/lbank_wrapper.go
  exchanges/poloniex/poloniex_test.go
  exchanges/poloniex/poloniex_wrapper.go
Labels: review me

#1177 OKX: Fix GetAvailableTransferChains bug
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1183 kraken: when fetching tradable pairs filter by status
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
Labels: review me

#1184 hitbtc: optimise fetching tradable pairs and tickers
  exchanges/hitbtc/hitbtc_test.go
  exchanges/hitbtc/hitbtc_wrapper.go
Labels: review me

#1180 exmo: refactor UpdateTickers function
  exchanges/exmo/exmo_test.go
  exchanges/exmo/exmo_wrapper.go
Labels: review me

#1175 OKX: Fix balance using funding account
  exchanges/okx/okx.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1186 OKX: Support exchange order limits
  exchanges/okx/okx_test.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1181 orders: Add AdjustBaseAmount
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/order/order_test.go
  exchanges/order/orders.go
Labels: review me, gcrc

#1195 OKX: Update to new savings module
  exchanges/okx/okx.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_type_convert.go
  exchanges/okx/okx_types.go
  exchanges/okx/ratelimit.go
Labels: review me

#1200 Okx: Fix fundingRate sub not sending instId
  exchanges/okx/okx_websocket.go
Labels: bug, review me

#1204 Okx: Fix GetFundingRateHistory limit
  exchanges/okx/okx.go
Labels: bug, review me

#1203 Okx: Fix ping handler
  exchanges/okx/okx_websocket.go
Labels: review me

#1201 wsManager: Fix IsRunning true before flushed
  engine/engine.go
  engine/engine_test.go
  engine/websocketroutine_manager.go
  engine/websocketroutine_manager_test.go
  engine/websocketroutine_manager_types.go
Labels: review me

#1058 exchanges: Update GateIO exchange to V4
  .gitignore
  config_example.json
  currency/code.go
  currency/code_types.go
  currency/pair.go
  currency/pair_test.go
  engine/websocketroutine_manager.go
  exchanges/asset/asset.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_convert.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
  exchanges/gateio/ratelimiter.go
  exchanges/kline/kline.go
  exchanges/kline/kline_test.go
  exchanges/kline/kline_types.go
  exchanges/request/request.go
  testdata/configtest.json
Labels: review me, gcrc
