Repository thrasher-corp/gocryptotrader, pull requests merged in 2023-12, with the labels that each got.

#1414 Kucoin: Fix unmarshalling of FuturesTicker resp
  exchanges/kucoin/kucoin_futures.go
  exchanges/kucoin/kucoin_futures_types.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/testdata/wsHandleData.json
  exchanges/sharedtestvalues/sharedtestvalues.go
Labels: review me, gcrc, high priority, test(s) fix

#1416 Okx: Fix GetBlockTrades and enhance test coverage
  exchanges/okx/okx.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
Labels: review me, high priority

#1401 BTSE: Fix duplicate pair errors on Million pairs (M_*)
  cmd/gctcli/commands.go
  cmd/gctcli/data_history.go
  cmd/gctcli/futures.go
  cmd/gctcli/trades.go
  common/common.go
  common/common_test.go
  config/config.go
  config_example.json
  currency/manager.go
  currency/manager_test.go
  currency/pair_methods.go
  currency/pair_test.go
  engine/apiserver_test.go
  exchanges/btse/btse.go
  exchanges/btse/btse_test.go
  exchanges/btse/btse_types.go
  exchanges/btse/btse_wrapper.go
  exchanges/itbit/itbit_wrapper.go
  exchanges/ticker/ticker.go
  exchanges/ticker/ticker_test.go
  testdata/configtest.json
Labels: review me, high priority, test(s) fix

#1407 Orderbook: Fix test failures on arm64
  exchanges/kline/weighted_price_test.go
  exchanges/orderbook/depth_test.go
  exchanges/orderbook/linked_list_test.go
Labels: review me, high priority, test(s) fix

#1413 OKX: Change float64 to convert.StringtoFloat64 in okx_types
  contrib/spellcheck/exclude_lines.txt
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1415 Types: Switch convert.StringToFloat64 to types.Number
  common/convert/convert.go
  common/convert/convert_test.go
  contrib/spellcheck/exclude_lines.txt
  contrib/spellcheck/ignore_words.txt
  exchanges/binance/binance_types.go
  exchanges/binance/ufutures_types.go
  exchanges/bybit/bybit.go
  exchanges/bybit/bybit_cfutures.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_usdcfutures.go
  exchanges/bybit/futures_type.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gemini/gemini_types.go
  exchanges/kucoin/kucoin_futures_types.go
  exchanges/okcoin/okcoin_types.go
  exchanges/okx/okx_types.go
  types/number.go
  types/number_test.go
Labels: review me

#1412 dispatch: Fix intermittent TestMuxPublish issue
  dispatch/dispatch.go
  dispatch/dispatch_test.go
Labels: review me, gcrc, szrc, high priority, test(s) fix

#1429 Exchanges: Convert bespoke Number types to types.Number
  exchanges/gateio/gateio_convert.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/kucoin/kucoin_convert.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/okcoin/okcoin_convert.go
  exchanges/okcoin/okcoin_test.go
  exchanges/okcoin/okcoin_types.go
  exchanges/okcoin/okcoin_websocket.go
  exchanges/okx/okx_type_convert.go
  exchanges/okx/okx_types.go
  types/number.go
Labels: review me, gcrc, szrc

#1422 CI: Add macOS, Windows x64 and Linux arm64 test support
  .appveyor.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/arm64.Dockerfile
  .github/workflows/linter.yml
  .github/workflows/tests.yml
  .travis.yml
  Makefile
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  codecov.yml
  codelingo.yaml
  database/testhelpers/test_helpers.go
  engine/engine_test.go
Labels: review me, szrc

#1427 Bitfinex: Fix UpdateTickers
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_wrapper.go
Labels: review me, szrc, test(s) fix

#1406 Bitstamp: Fix GetWithdrawalRequests/GetWithdrawalsHistory date parsing and enhance test coverage
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/bitstamp/bitstamp_wrapper.go
  testdata/http_mock/bitstamp/bitstamp.json
Labels: review me
