Repository thrasher-corp/gocryptotrader, pull requests merged in 2023-07, with the labels that each got.

#1251 Kraken: Fix auth request regression
  exchanges/kraken/kraken.go
Labels: review me

#1250 credentials: Fix issue with external package usage
  exchanges/account/credentials.go
  exchanges/credentials.go
  exchanges/credentials_test.go
Labels: review me

#1246 common: remove `SimpleTimeFormat` const for time package layout const `DateTime`
  .appveyor.yml
  backtester/btcli/commands.go
  backtester/config/strategyconfig.go
  backtester/config/strategyconfigbuilder/main.go
  backtester/eventhandlers/statistics/printresults.go
  backtester/eventhandlers/strategies/rsi/rsi.go
  backtester/eventhandlers/strategies/top2bottom2/top2bottom2.go
  cmd/gctcli/commands.go
  cmd/gctcli/data_history.go
  cmd/gctcli/futures.go
  cmd/gctcli/technical_analysis.go
  cmd/gctcli/trades.go
  common/common.go
  engine/datahistory_manager.go
  engine/rpcserver.go
  exchanges/binance/binance.go
  exchanges/binance/binance_test.go
  exchanges/binanceus/binanceus.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bithumb/bithumb.go
  exchanges/bithumb/bithumb_websocket.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/btse/btse.go
  exchanges/kline/kline.go
  exchanges/poloniex/poloniex_websocket.go
  exchanges/poloniex/poloniex_wrapper.go
Labels: low priority, review me

#1196 dispatcher: prevent job limit errors with no subscribers
  dispatch/dispatch.go
  dispatch/dispatch_test.go
  dispatch/dispatch_types.go
  dispatch/mux.go
Labels: low priority, review me

#1257 Okx: Log auth websocket connection errors
  exchanges/okx/okx_websocket.go
Labels: review me

#1259 standards test: ignore CheckOrderExecutionLimits func
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
Labels: bug, review me

#1258 gctcli: Add command line parameter to ignore default context timeout
  cmd/gctcli/main.go
Labels: review me

#1238 engine: Fix Start method data race on err var
  engine/engine.go
Labels: bug, review me

#1229 SyncManager: Optimise and fixes
  engine/subsystem_types.go
  engine/sync_manager.go
  engine/sync_manager_test.go
  engine/sync_manager_types.go
Labels: review me

#1266 go.mod: bump go version to 1.20 from 1.17
  exchanges/binance/binance_live_test.go
  exchanges/binance/binance_mock_test.go
  exchanges/bitstamp/bitstamp_live_test.go
  exchanges/bitstamp/bitstamp_mock_test.go
  exchanges/gemini/gemini_live_test.go
  exchanges/gemini/gemini_mock_test.go
  exchanges/poloniex/poloniex_live_test.go
  exchanges/poloniex/poloniex_mock_test.go
  exchanges/zb/zb_live_test.go
  exchanges/zb/zb_mock_test.go
  go.mod
  go.sum
Labels: review me

#1240 Okx: Fix panic during shutdown due to race
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1265 Bitstamp: Fix USDT balance not loading
  exchanges/bitstamp/bitstamp.go
  exchanges/bitstamp/bitstamp_test.go
  testdata/http_mock/bitstamp/bitstamp.json
Labels: bug, review me

#1267 Kraken: Fix Balances reporting 0 Free
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
Labels: review me

#1273 gRPC: Add stream authentication to gRPC server
  backtester/engine/grpcserver.go
  engine/rpcserver.go
Labels: review me

#1276 bitfinex: fix websocket subscribing issue caused by formatting
  exchanges/bitfinex/bitfinex_websocket.go
Labels: bug, review me

#1255 Kraken: Load order execution limits for tradable pairs
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
Labels: review me

#1279 Kraken: fix websocket orderbook processing
  exchanges/bittrex/bittrex_ws_orderbook.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_websocket.go
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
  exchanges/orderbook/orderbook_types.go
Labels: bug, review me

#1285 Kraken: Fix ws orderType parsing
  exchanges/kraken/kraken_websocket.go
Labels: review me

#1284 Orders: Fix Pending status not parsed
  exchanges/order/orders.go
Labels: review me

#1283 Kraken: Fix WS new order pair symbol format
  exchanges/kraken/kraken_wrapper.go
Labels: review me

#1264 Bitstamp: Implement UpdateOrderExecutionLimits and testing
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_type_convert.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/bitstamp/bitstamp_wrapper.go
Labels: review me

#1269 Bitfinex: Implement UpdateOrderExecutionLimits and tests
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
  exchanges/bitfinex/bitfinex_wrapper.go
Labels: review me

#1281 gateio: Implement UpdateOrderExecutionLimits for spot instruments
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_wrapper.go
Labels: review me

#1286 Order: Fix AmountStepIncrementSize conforms check
  exchanges/order/limits.go
Labels: review me
