Repository thrasher-corp/gocryptotrader, pull requests merged in 2023-11, with the labels that each got.

#1353 Bitfinex: Websocket subscription improvements
  docs/ADD_NEW_EXCHANGE.md
  exchanges/binance/binance_websocket.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bitfinex/testdata/getErrResp.json
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/bittrex/bittrex_websocket.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/btse/btse_websocket.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_ws_cfutures.go
  exchanges/bybit/bybit_ws_futures.go
  exchanges/bybit/bybit_ws_ufutures.go
  exchanges/coinbasepro/coinbasepro_websocket.go
  exchanges/coinut/coinut_websocket.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_ws_option.go
  exchanges/gemini/gemini_websocket.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/huobi/huobi_websocket.go
  exchanges/kraken/kraken_websocket.go
  exchanges/okcoin/okcoin_websocket.go
  exchanges/okx/okx_websocket.go
  exchanges/poloniex/poloniex_websocket.go
  exchanges/stream/stream_match.go
  exchanges/stream/stream_match_test.go
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
  go.mod
  go.sum
  testdata/configtest.json
Labels: review me

#1386 Bitfinex: replace errTypeAssert with common.GetTypeAssertError
  exchanges/bitfinex/bitfinex.go
Labels: review me, gcrc

#1369 Kucoin: Add order execution limits
  cmd/exchange_template/wrapper_file.tmpl
  config/config.go
  exchanges/alphapoint/alphapoint_wrapper.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitflyer/bitflyer_wrapper.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bittrex/bittrex_wrapper.go
  exchanges/btse/btse_wrapper.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/exmo/exmo_wrapper.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/itbit/itbit_wrapper.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/lbank/lbank_wrapper.go
  exchanges/poloniex/poloniex_wrapper.go
  exchanges/yobit/yobit_wrapper.go
  exchanges/zb/zb_wrapper.go
Labels: review me, gcrc

#1380 kucoin: fix spot order unmarshal bug
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_wrapper.go
Labels: bug, review me, gcrc

#1392 Kucoin: Fix ProcessMarketSnapshot and add a test
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/kucoin/testdata/wsMarketSnapshot.json
  testdata/configtest.json
Labels: review me, gcrc

#1400 Engine: Fix panic when exchange errors
  engine/helpers_test.go
Labels: review me

#1385 Gateio: Add function GetHistoricalFundingRates
  exchanges/fundingrate/fundingrate_types.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_wrapper.go
Labels: review me

#1395 Engine: Remove Default Forex Provider
  CONTRIBUTORS
  README.md
  cmd/documentation/currency_templates/fx.tmpl
  cmd/documentation/currency_templates/fx_exchangeratehost.tmpl
  config/config_types.go
  currency/conversion_test.go
  currency/currency_types.go
  currency/forexprovider/README.md
  currency/forexprovider/currencylayer/currencylayer_test.go
  currency/forexprovider/currencylayer/currencylayer_types.go
  currency/forexprovider/exchangerate.host/README.md
  currency/forexprovider/exchangerate.host/exchangerate.go
  currency/forexprovider/exchangerate.host/exchangerate_test.go
  currency/forexprovider/exchangerate.host/exchangerate_types.go
  currency/forexprovider/forexprovider.go
  currency/mock_provider_test.go
  currency/storage.go
  currency/storage_test.go
  engine/engine.go
  engine/engine_types.go
  engine/sync_manager.go
  main.go
Labels: review me

#1405 Okx: Fix GetInsuranceFundInformation "" resp
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
  testdata/configtest.json
Labels: review me, szrc
