Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-09, with the labels that each got.

#1578 exchanges/websocket: update websocket rate limiting to use requester rate limiting functionality.
  exchanges/binance/binance_types.go
  exchanges/binance/binance_wrapper.go
  exchanges/binanceus/binanceus_types.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bithumb/bithumb_websocket.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/btse/btse_websocket.go
  exchanges/bybit/bybit_inverse_websocket.go
  exchanges/bybit/bybit_linear_websocket.go
  exchanges/bybit/bybit_options_websocket.go
  exchanges/bybit/ratelimit.go
  exchanges/coinbasepro/coinbasepro_websocket.go
  exchanges/coinut/coinut.go
  exchanges/coinut/coinut_websocket.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/deribit/deribit_websocket.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gemini/gemini_websocket.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/huobi/huobi_websocket.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/poloniex/poloniex_websocket.go
  exchanges/request/limit.go
  exchanges/request/request_test.go
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
Labels: review me, high priority

#1647 gateio: fix and optimise time
  exchanges/gateio/gateio_convert.go
  exchanges/gateio/gateio_test.go
Labels: bug, review me

#1640 stream: Add verbosity to outbound requests that also returns responses
  exchanges/request/request.go
  exchanges/request/request_test.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
Labels: review me

#1631 common: Replace StringDataCompare with slices.Contains and cleanup string funcs
  cmd/apichecker/apicheck.go
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  common/common.go
  common/common_test.go
  config/config.go
  config/config_test.go
  currency/forexprovider/base/base_interface.go
  docs/ADD_NEW_EXCHANGE.md
  engine/engine.go
  engine/engine_test.go
  engine/helpers.go
  engine/helpers_test.go
  engine/order_manager.go
  exchanges/asset/asset_test.go
  exchanges/binance/binance_cfutures.go
  exchanges/binance/binance_ufutures.go
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_types.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/bybit/bybit.go
  exchanges/coinbasepro/coinbasepro.go
  exchanges/huobi/huobi_cfutures.go
  exchanges/huobi/huobi_futures.go
  exchanges/kraken/kraken_futures.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_futures.go
  exchanges/poloniex/poloniex_wrapper.go
  gctscript/modules/gct/exchange.go
  portfolio/banking/banking.go
  portfolio/portfolio.go
Labels: review me

#1641 stream/okx: allow rate limit definitions to be used by the stream package
  exchanges/binance/binance_websocket.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bithumb/bithumb_websocket.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/btse/btse_websocket.go
  exchanges/bybit/bybit_inverse_websocket.go
  exchanges/bybit/bybit_linear_websocket.go
  exchanges/bybit/bybit_options_websocket.go
  exchanges/bybit/bybit_websocket.go
  exchanges/coinbasepro/coinbasepro_websocket.go
  exchanges/coinut/coinut_websocket.go
  exchanges/deribit/deribit_websocket.go
  exchanges/deribit/deribit_websocket_eps.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
  exchanges/gemini/gemini_websocket.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/huobi/huobi_websocket.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/okx/ratelimit.go
  exchanges/poloniex/poloniex_websocket.go
  exchanges/request/limit.go
  exchanges/request/request_test.go
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
Labels: review me, gcrc

#1438 exchanges: Kucoin Update
  .gitignore
  common/common.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_futures.go
  exchanges/kucoin/kucoin_futures_types.go
  exchanges/kucoin/kucoin_ratelimit.go
  exchanges/kucoin/kucoin_ratelimit_test.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/order/order_types.go
Labels: review me, gcrc, szrc, high priority

#1649 CoinbasePro: Skip specific tests due to API deprecation
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  engine/engine_test.go
  exchanges/coinbasepro/coinbasepro_test.go
Labels: review me, high priority, test(s) fix

#1652 Binance: Fix occassional race failure on TestWsOrderExecutionReport
  exchanges/binance/binance_test.go
Labels: review me, test(s) fix

#1599 GateIO: Add Subscription configuration
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
  go.mod
  go.sum
  testdata/configtest.json
Labels: review me, szrc
