Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-06, with the labels that each got.

#1558 Deribit: bug fixes, test fixes and implement GetCurrencyTradeURL
  exchanges/deribit/deribit.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_websocket.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/kline/kline.go
  exchanges/orderbook/orderbook.go
Labels: bug, review me, szrc

#1532 gateio: update FuturesAccount and Position struct
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_convert.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
Labels: bug, review me, high priority

#1550 BTSE: Various fixes
  common/common.go
  exchanges/asset/asset.go
  exchanges/btse/btse.go
  exchanges/btse/btse_test.go
  exchanges/btse/btse_types.go
  exchanges/btse/btse_wrapper.go
  exchanges/order/limits.go
Labels: review me, szrc, high priority, test(s) fix
