Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-05, with the labels that each got.

#1530 btcmarkets: remove trailing slash on markets/ticker strings and update endpoint pathways
  exchanges/btcmarkets/btcmarkets.go
Labels: bug, review me, high priority

#1510 Bitstamp: Add missing API fields
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/bitstamp/bitstamp_wrapper.go
  testdata/http_mock/bitstamp/bitstamp.json
Labels: review me, gcrc

#1525 Test: Internal exchange coverage
  exchanges/binance/binance_live_test.go
  exchanges/binance/binance_mock_test.go
  exchanges/kraken/kraken_test.go
  exchanges/kucoin/kucoin_test.go
  internal/testing/exchange/exchange.go
  internal/testing/exchange/exchange_test.go
  internal/testing/exchange/testdata/http.json
  internal/testing/utils/path.go
  internal/testing/utils/path_test.go
Labels: review me, szrc

#1534 Tests: Various race fixes and move TestFixtureToDataHandler
  backtester/eventhandlers/exchange/slippage/slippage_test.go
  currency/manager.go
  currency/manager_test.go
  currency/pair.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitflyer/bitflyer_test.go
  exchanges/bitstamp/bitstamp_test.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/gateio/gateio.go
  exchanges/kraken/kraken_test.go
  exchanges/kucoin/kucoin_test.go
  exchanges/okx/okx.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/sharedtestvalues/sharedtestvalues.go
  internal/testing/exchange/exchange.go
  testdata/configtest.json
Labels: review me, szrc, test(s) fix

#1545 currency/manager: remove deadlock potential in concurrent operations
  currency/manager.go
  exchanges/exchange_test.go
Labels: bug, review me, high priority

#1554 Linter: Spelling fixes
  backtester/engine/grpcserver.go
  cmd/gctcli/commands.go
  contrib/spellcheck/ignore_words.txt
  currency/code.go
  currency/currencies.go
  currency/pairs.go
  exchanges/asset/asset.go
Labels: bug, review me, test(s) fix

#1082 exchanges: Add Deribit exchange support
  CONTRIBUTORS
  LICENSE
  README.md
  cmd/documentation/documentation.go
  cmd/documentation/exchanges_templates/deribit.tmpl
  cmd/documentation/exchanges_templates/exchanges_trade_readme.tmpl
  cmd/documentation/root_templates/root_readme.tmpl
  cmd/exchange_wrapper_issues/wrapperconfig.json
  config_example.json
  contrib/spellcheck/exclude_lines.txt
  currency/code_types.go
  docs/ADD_NEW_EXCHANGE.md
  docs/MULTICHAIN_TRANSFER_SUPPORT.md
  docs/OHLCV.md
  engine/helpers.go
  exchanges/asset/asset.go
  exchanges/asset/asset_test.go
  exchanges/deribit/README.md
  exchanges/deribit/deribit.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_types.go
  exchanges/deribit/deribit_websocket.go
  exchanges/deribit/deribit_websocket_eps.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/deribit/ratelimit.go
  exchanges/futures/contract.go
  exchanges/kline/kline.go
  exchanges/kline/kline_test.go
  exchanges/kline/kline_types.go
  exchanges/support.go
  exchanges/trade/README.md
  testdata/configtest.json
  testdata/exchangelist.csv
Labels: review me, high priority
