Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-12, with the labels that each got.

#1715 types/time: filter string that cannot be a unix timestamp
  types/time.go
  types/time_test.go
Labels: bug, review me

#1618 Bithumb: Add subscription configuration
  exchanges/bithumb/bithumb_websocket.go
  exchanges/bithumb/bithumb_websocket_test.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/subscription/subscription.go
Labels: review me, gcrc, szrc, medium priority

#1693 Subscriptions: Respect DisableAssetWebsocketSupport for assets
  exchanges/bitmex/bitmex_test.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/gateio/gateio_test.go
  exchanges/subscription/fixtures_test.go
  exchanges/subscription/list.go
  exchanges/subscription/template.go
  exchanges/subscription/template_test.go
  testdata/configtest.json
Labels: bug, review me, gcrc, szrc

#1671 Config: Add versioning
  cmd/config/config.go
  cmd/config/config_test.go
  common/common.go
  config/config.go
  config/config_encryption.go
  config/config_encryption_test.go
  config/config_test.go
  config/config_types.go
  config/versions/fixtures_test.go
  config/versions/v0.go
  config/versions/v0/types.go
  config/versions/v1.go
  config/versions/v1/types.go
  config/versions/v1_test.go
  config/versions/v2.go
  config/versions/v2_test.go
  config/versions/versions.go
  config/versions/versions_test.go
  engine/apiserver_test.go
  engine/engine.go
  go.mod
  go.sum
Labels: review me, gcrc, szrc

#1620 Bitstamp: Add subscription configuration
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/bitstamp/bitstamp_wrapper.go
  testdata/configtest.json
Labels: review me, gcrc, medium priority

#1733 gateio: update rate limit definitions
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/ratelimiter.go
  exchanges/gateio/ratelimiter_test.go
Labels: bug, review me, gcrc, high priority, test(s) fix

#1639 HitBTC: Add Subscription Configuration
  cmd/documentation/exchanges_templates/hitbtc.tmpl
  exchanges/hitbtc/README.md
  exchanges/hitbtc/hitbtc_test.go
  exchanges/hitbtc/hitbtc_types.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/hitbtc/hitbtc_wrapper.go
  testdata/configtest.json
Labels: review me, gcrc, szrc, medium priority

#1753 exchanges: Fix GateIO/Coinbase test failures and OKX race
  exchanges/coinbasepro/coinbasepro_test.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/okx/okx_test.go
Labels: review me, high priority, test(s) fix

#1598 websocket/gateio: Add request functions for websocket multi-connection [SPOT]
  engine/engine.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/exchange.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_websocket_delivery_futures.go
  exchanges/gateio/gateio_websocket_futures.go
  exchanges/gateio/gateio_websocket_option.go
  exchanges/gateio/gateio_websocket_request_spot.go
  exchanges/gateio/gateio_websocket_request_spot_test.go
  exchanges/gateio/gateio_websocket_request_types.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/stream/stream_match.go
  exchanges/stream/stream_match_test.go
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
Labels: review me, high priority
