Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-03, with the labels that each got.

#1371 Kucoin: Changes default subscription channel for tickers and orderbooks
  engine/websocketroutine_manager.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/kucoin/kucoin_futures.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/kucoin/kucoin_wrapper.go
Labels: bug, review me, gcrc, high priority

#1404 gateio/kucoin: assortment of fixes
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  currency/pairs.go
  currency/pairs_test.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/order/order_types.go
Labels: bug, review me, gcrc, high priority

#1471 Websocket: Prevent panic on Disconnect/Connect
  exchanges/stream/websocket.go
  exchanges/stream/websocket_test.go
Labels: bug, review me, szrc, high priority

#1489 Kraken: Fix TestUpdateOrderExecutionLimits
  exchanges/kraken/kraken_test.go
Labels: review me, gcrc, szrc, high priority, test(s) fix

#1495 Coinut: Fix websocket not parsing instruments, improve nonce matching and error handling
  exchanges/coinut/coinut_types.go
  exchanges/coinut/coinut_websocket.go
Labels: bug, review me, gcrc

#1503 Tests: Abstract UpdatePairsOnce
  exchanges/bitfinex/bitfinex_test.go
  exchanges/btse/btse_test.go
  exchanges/gateio/gateio_test.go
  exchanges/okx/okx_test.go
  internal/testing/exchange/exchange.go
Labels: review me

#1486 common/timedmutex: clean and improve
  common/timedmutex/timed_mutex.go
  common/timedmutex/timed_mutex_test.go
  common/timedmutex/timed_mutex_types.go
Labels: low priority, review me, gcrc

#1507 request: fix intermittent race when verbose and reading the body in different routines
  exchanges/request/request.go
Labels: bug, review me, gcrc
