Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-11, with the labels that each got.

#1601 Bybit: Add subscription configuration for spot
  exchanges/bybit/bybit_inverse_websocket.go
  exchanges/bybit/bybit_linear_websocket.go
  exchanges/bybit/bybit_options_websocket.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
  exchanges/orderbook/orderbook_types.go
  exchanges/stream/buffer/buffer.go
  exchanges/subscription/subscription.go
Labels: review me, gcrc, medium priority

#1702 gateio: Update contract settlement currencies
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_wrapper.go
Labels: review me, high priority, test(s) fix

#1680 bybit: Add OrderbookLastUpdated field and ensure timestamp usage is correct
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_websocket.go
Labels: bug, review me

#1604 Huobi: Add subscription configuration
  cmd/documentation/exchanges_templates/huobi.tmpl
  exchanges/huobi/README.md
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_websocket.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_websocket.go
  exchanges/subscription/subscription.go
  testdata/configtest.json
Labels: review me, medium priority

#1682 stream/buffer: Improve orderbook verification conditions and fix TestUpdateByIDAndAction test
  exchanges/orderbook/orderbook.go
  exchanges/orderbook/orderbook_test.go
  exchanges/stream/buffer/buffer.go
  exchanges/stream/buffer/buffer_test.go
Labels: review me, high priority, test(s) fix

#1707 Huobi: Fix invalid contract type error when autoUpdatePairs is false
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_wrapper.go
Labels: bug, review me

#1709 Huobi: Fix GetAvailableTransferChains returning unavailable chains
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_types.go
  exchanges/huobi/huobi_wrapper.go
Labels: bug

#1616 BTSE: Add subscription configuration
  exchanges/btse/btse_test.go
  exchanges/btse/btse_websocket.go
  exchanges/btse/btse_wrapper.go
  testdata/configtest.json
Labels: review me, medium priority

#1723 gateio: Remove `listOfAssetsCurrencyPairEnabledFor` method and optimise websocket asset processing
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
Labels: review me, medium priority

#1593 currency: fix edge case on NewCode where all string characters are digits
  currency/code.go
  currency/code_test.go
  currency/code_types.go
  currency/manager.go
  currency/manager_test.go
  currency/pair.go
  currency/pair_test.go
  currency/pairs.go
  currency/pairs_test.go
  currency/storage.go
  exchanges/account/account.go
  exchanges/bitfinex/bitfinex_wrapper.go
  gctscript/wrappers/gct/gctwrapper_test.go
Labels: review me, gcrc, medium priority

#1724 Assets: Fix LinearContracts support
  exchanges/asset/asset.go
  exchanges/asset/asset_test.go
  exchanges/order/order_test.go
Labels: bug, review me

#1726 order: Add `Side` type MarshalJSON method
  exchanges/order/order_test.go
  exchanges/order/orders.go
Labels: review me

#1617 common/math: Add math.Abs to PercentageDifference calculation
  common/math/math.go
  common/math/math_test.go
  engine/datahistory_manager.go
  exchanges/orderbook/calculator.go
  exchanges/orderbook/tranches.go
Labels: low priority, review me
