Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-10, with the labels that each got.

#1648 types: Add Time type from Gateio and share across codebase
  common/convert/convert.go
  common/convert/convert_test.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_types.go
  exchanges/binance/cfutures_types.go
  exchanges/binance/type_convert.go
  exchanges/binance/ufutures_types.go
  exchanges/binanceus/binanceus_test.go
  exchanges/binanceus/type_convert.go
  exchanges/bithumb/bithumb_types.go
  exchanges/bithumb/bithumb_websocket_types.go
  exchanges/bithumb/convert.go
  exchanges/bithumb/convert_test.go
  exchanges/bitstamp/bitstamp_type_convert.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/testdata/wsTicker.json
  exchanges/deribit/deribit_types.go
  exchanges/gateio/gateio_convert.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_futures.go
  exchanges/kucoin/kucoin_futures_types.go
  exchanges/kucoin/kucoin_types.go
  exchanges/okx/okx_types.go
  types/time.go
  types/time_test.go
Labels: bug, review me, gcrc, medium priority

#1655 Huobi: Fix intermittent UpdateTickers failure on expiry
  exchanges/huobi/huobi.go
  exchanges/huobi/huobi_futures.go
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_types.go
  exchanges/huobi/huobi_wrapper.go
Labels: bug, review me, test(s) fix

#1659 Kraken: Fix TestGetFuturesOrderbook and consolidate test pairs
  exchanges/kraken/kraken_test.go
Labels: review me, test(s) fix

#1660 Huobi: Remove suspended API endpoints
  exchanges/huobi/huobi_cfutures.go
  exchanges/huobi/huobi_futures.go
  exchanges/huobi/huobi_test.go
Labels: review me, test(s) fix

#1587 Kraken: Subscription improvements
  common/convert/convert.go
  common/convert/convert_test.go
  currency/pair.go
  exchanges/binance/binance_test.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kraken/mock_ws_test.go
  exchanges/kraken/testdata/wsHandleData.json
  exchanges/kraken/testdata/wsOpenTrades.json
  exchanges/kucoin/kucoin_websocket.go
  exchanges/stream/websocket.go
  exchanges/subscription/keys.go
  exchanges/subscription/keys_test.go
  exchanges/subscription/subscription.go
  internal/testing/exchange/exchange.go
  internal/testing/exchange/exchange_test.go
  testdata/configtest.json
Labels: review me, szrc

#1629 Subscriptions: Add List.Enabled, List.Public and List.Private
  exchanges/exchange.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/subscription/list.go
  exchanges/subscription/list_test.go
Labels: review me, gcrc, szrc, medium priority

#1580 websocket/gateio: Support multi connection management and integrate with GateIO
  docs/ADD_NEW_EXCHANGE.md
  engine/rpcserver.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_websocket.go
  exchanges/binance/binance_wrapper.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bithumb/bithumb_websocket.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/btse/btse_websocket.go
  exchanges/btse/btse_wrapper.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/coinbasepro/coinbasepro_websocket.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinut/coinut_websocket.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/exchange.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
  exchanges/gemini/gemini_websocket.go
  exchanges/gemini/gemini_wrapper.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/huobi/huobi_websocket.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/poloniex/poloniex_websocket.go
  exchanges/poloniex/poloniex_wrapper.go
  exchanges/protocol/features.go
  exchanges/stream/README.md
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
  internal/testing/exchange/exchange.go
  internal/testing/exchange/exchange_test.go
  internal/testing/websocket/mock.go
Labels: bug, review me, gcrc, high priority

#1675 Bybit: Add CryptoChain field to GetWithdrawalsHistory wrapper
  exchanges/bybit/bybit_wrapper.go
Labels: review me, gcrc, szrc

#1679 huobi: ticker swap amount and volume values
  exchanges/huobi/huobi_wrapper.go
Labels: bug, review me, gcrc

#1597 Bitfinex: Add subscription configuration and templating
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/subscription/README.md
  internal/testing/subscriptions/subscriptions.go
  testdata/configtest.json
Labels: review me, gcrc

#1658 gateio: Small update on fields and subscriptions
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
Labels: review me, gcrc

#1586 Bitmex: Subscription templating
  exchanges/bitmex/bitmex_test.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitmex/bitmex_websocket_types.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/exchange.go
  testdata/configtest.json
Labels: review me, gcrc, medium priority

#1669 Kucoin: Abstract a subscriptionNames for assets solution
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_websocket.go
Labels: review me, high priority

#1635 Subscriptions: Relax subscription validation for non-existent pairs
  exchanges/subscription/template.go
  exchanges/subscription/template_test.go
Labels: bug, review me, szrc, high priority

#1685 Bitmex: Fix handling index records in WS trade stream
  exchanges/bitmex/bitmex_test.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitmex/bitmex_websocket_types.go
  exchanges/exchange.go
  exchanges/exchange_test.go
Labels: bug, review me

#1695 Tests: Fix fail on vendored modules
  internal/testing/utils/path_test.go
Labels: review me, test(s) fix
