Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-01, with the labels that each got.

#1442 Binance: Fix GetHistoricTrades failing live
  exchanges/binance/binance.go
  exchanges/binance/binance_test.go
Labels: review me, gcrc, test(s) fix

#1421 CoinbasePRO: Fix websocket subscription errors
  exchanges/coinbasepro/coinbasepro_websocket.go
Labels: bug, review me, szrc

#1379 requester: purge max request jobs
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  engine/engine.go
  engine/engine_types.go
  exchanges/binance/binance_live_test.go
  exchanges/binance/binance_mock_test.go
  exchanges/bybit/bybit_live_test.go
  exchanges/bybit/bybit_mock_test.go
  exchanges/gateio/gateio_test.go
  exchanges/huobi/huobi_test.go
  exchanges/kucoin/kucoin_test.go
  exchanges/okx/okx_test.go
  exchanges/request/request.go
  exchanges/request/request_test.go
  exchanges/request/request_types.go
  main.go
Labels: review me

#1443 Dispatch: Fix race during stop
  dispatch/dispatch.go
  dispatch/dispatch_test.go
  dispatch/dispatch_types.go
Labels: review me, szrc, high priority, test(s) fix

#1439 Huobi: Implement ticker batching
  exchanges/huobi/huobi.go
  exchanges/huobi/huobi_futures.go
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_types.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/kraken/kraken_test.go
Labels: review me

#1451 Kraken: Improve ticker batch performance
  exchanges/kraken/futures_types.go
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/ticker/ticker_types.go
Labels: review me

#1450 ZB: Remove exchange implementation
  README.md
  cmd/documentation/exchanges_templates/exchanges_trade_readme.tmpl
  cmd/documentation/exchanges_templates/zb.tmpl
  cmd/documentation/root_templates/root_readme.tmpl
  config_example.json
  docs/ADD_NEW_EXCHANGE.md
  docs/MULTICHAIN_TRANSFER_SUPPORT.md
  docs/OHLCV.md
  engine/helpers.go
  exchanges/support.go
  exchanges/trade/README.md
  exchanges/zb/README.md
  exchanges/zb/ratelimit.go
  exchanges/zb/zb.go
  exchanges/zb/zb_live_test.go
  exchanges/zb/zb_mock_test.go
  exchanges/zb/zb_test.go
  exchanges/zb/zb_types.go
  exchanges/zb/zb_websocket.go
  exchanges/zb/zb_websocket_types.go
  exchanges/zb/zb_wrapper.go
  testdata/configtest.json
  testdata/exchangelist.csv
  testdata/http_mock/zb/zb.json
Labels: review me

#1454 Bitfinex: Fix panic on TestUpdateTickers
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
Labels: review me, test(s) fix
