Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-07, with the labels that each got.

#1538 Bybit: Fix WS ticker processing
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/bybit/testdata/wsTicker.json
  exchanges/ticker/ticker.go
  exchanges/ticker/ticker_types.go
  testdata/configtest.json
Labels: bug, review me, high priority

#1552 protocol/order: adds additional fields for trading requirements
  cmd/exchange_template/wrapper_file.tmpl
  engine/order_manager.go
  engine/order_manager_test.go
  exchanges/alphapoint/alphapoint_wrapper.go
  exchanges/binance/binance_wrapper.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/btse/btse_wrapper.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/exchange_types.go
  exchanges/exmo/exmo_wrapper.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gemini/gemini_wrapper.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/interfaces.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/lbank/lbank_wrapper.go
  exchanges/okcoin/okcoin_wrapper.go
  exchanges/okx/okx_wrapper.go
  exchanges/order/order_test.go
  exchanges/order/orders.go
  exchanges/poloniex/poloniex_wrapper.go
  exchanges/protocol/features.go
  exchanges/yobit/yobit_wrapper.go
Labels: review me

#1566 currency: Make pairs.Add variadic
  backtester/funding/trackingcurrencies/trackingcurrencies_test.go
  currency/pairs.go
  currency/pairs_test.go
  exchanges/sharedtestvalues/sharedtestvalues.go
  exchanges/subscription/subscription.go
Labels: review me

#1561 log: allow external definition of log handling
  log/custom_log_hooks.go
  log/custom_log_hooks_test.go
  log/loggers.go
Labels: low priority, review me, gcrc

#1582 Subscriptions: Fix subscription.Clone Params and Pairs
  exchanges/subscription/subscription.go
  exchanges/subscription/subscription_test.go
Labels: bug, review me

#1583 Okx: Fix TestGetBlockTrade transient fail
  exchanges/okx/okx_test.go
Labels: review me, test(s) fix

#1573 Gateio: Add unified account API endpoint support
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
Labels: review me, gcrc

#1584 orders/gateio: Add `GetTradeAmount` method to order.Submit type
  exchanges/gateio/gateio_wrapper.go
  exchanges/order/order_test.go
  exchanges/order/orders.go
Labels: review me

#1592 Subscriptions: Add List.Clone
  exchanges/subscription/list.go
  exchanges/subscription/list_test.go
  exchanges/subscription/subscription_test.go
Labels: review me

#1591 Kraken: Simplify REST error and result handling
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_futures.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
Labels: review me
