Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-02, with the labels that each got.

#1423 Bitstamp/Kraken: Enhance test coverage
  exchanges/bitstamp/bitstamp_mock_test.go
  exchanges/bitstamp/bitstamp_test.go
  exchanges/bitstamp/bitstamp_types.go
  exchanges/kraken/kraken_test.go
  testdata/http_mock/bitstamp/bitstamp.json
Labels: review me, test(s) fix

#1456 engine/gRPC proxy: Fix mux regression and add test coverage
  engine/helpers.go
  engine/rpcserver.go
  engine/rpcserver_test.go
Labels: review me, szrc

#1452 Binance: Improve wsHandleData performance
  exchanges/binance/binance_test.go
  exchanges/binance/binance_types.go
  exchanges/binance/binance_websocket.go
  exchanges/binance/testdata/wsHandleData.json
Labels: review me

#1467 Deps: Require go 1.21
  go.mod
Labels: review me

#1464 Binance: Fix UpdateOrderExecutionLimits margin test
  exchanges/binance/binance.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_types.go
  exchanges/binance/binance_wrapper.go
  exchanges/btse/btse_test.go
Labels: bug, review me, szrc, test(s) fix

#1463 ItBit: Remove exchange implementation
  README.md
  cmd/apichecker/apicheck.go
  cmd/apichecker/apicheck_test.go
  cmd/apichecker/testupdates.json
  cmd/apichecker/updates.json
  cmd/documentation/exchanges_templates/exchanges_trade_readme.tmpl
  cmd/documentation/exchanges_templates/itbit.tmpl
  cmd/documentation/root_templates/root_readme.tmpl
  cmd/exchange_wrapper_coverage/main.go
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  config_example.json
  docs/ADD_NEW_EXCHANGE.md
  docs/MULTICHAIN_TRANSFER_SUPPORT.md
  docs/OHLCV.md
  engine/engine_test.go
  engine/helpers.go
  exchanges/itbit/README.md
  exchanges/itbit/itbit.go
  exchanges/itbit/itbit_test.go
  exchanges/itbit/itbit_types.go
  exchanges/itbit/itbit_wrapper.go
  exchanges/support.go
  exchanges/trade/README.md
  testdata/configtest.json
  testdata/exchangelist.csv
Labels: review me, szrc

#1484 Common: Fix fmt msg lost in AppendError().Error()
  common/common.go
  common/common_test.go
Labels: bug

#1485 Kucoin: Fix transient test failure on XMR
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/testdata/wsMarketSnapshot.json
  testdata/configtest.json
Labels: review me, test(s) fix

#1478 account: fix balance issue returning only one balance
  exchanges/account/account.go
  exchanges/binance/binance_wrapper.go
Labels: bug, review me, szrc
