Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-08, with the labels that each got.

#1579 Kucoin: Add subscription templating and various fixes
  README.md
  cmd/documentation/exchanges_templates/kucoin.tmpl
  cmd/documentation/exchanges_templates/subscription.tmpl
  common/common.go
  common/common_test.go
  currency/manager.go
  currency/manager_test.go
  currency/pairs.go
  currency/pairs_test.go
  exchanges/asset/asset.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/exchange.go
  exchanges/kucoin/README.md
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/kucoin/testdata/wsHandleData.json
  exchanges/orderbook/orderbook.go
  exchanges/subscription/README.md
  exchanges/subscription/fixtures_test.go
  exchanges/subscription/list.go
  exchanges/subscription/list_test.go
  exchanges/subscription/template.go
  exchanges/subscription/template_test.go
  exchanges/subscription/testdata/errors.tmpl
  exchanges/subscription/testdata/subscriptions.tmpl
Labels: review me, szrc, high priority

#1590 orderbook/gateio: add field `UpdatePushedAt` and `InsertedAt` for specific websocket updates
  engine/rpcserver_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
  exchanges/orderbook/orderbook.go
  exchanges/orderbook/orderbook_types.go
  exchanges/orderbook/tranches_test.go
  exchanges/stream/buffer/buffer.go
  exchanges/stream/buffer/buffer_test.go
Labels: low priority, review me, gcrc

#1611 Kraken: Fix TestGetOpenInterest
  common/common.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_websocket.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_futures.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_websocket.go
Labels: review me, szrc, high priority, test(s) fix

#1556 currency/exchanges: Add bespoke exchange translator and pair matching helper
  currency/code_types.go
  currency/translation.go
  currency/translation_test.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/exchange_types.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/okx/okx.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: review me

#1581 stream/match: Reduce complexity and limit locking when match occurs
  exchanges/binance/binance_websocket.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bybit/bybit_websocket.go
  exchanges/coinut/coinut_websocket.go
  exchanges/deribit/deribit_websocket.go
  exchanges/deribit/deribit_websocket_eps.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_ws_delivery_futures.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/gateio/gateio_ws_option.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/huobi/huobi_websocket.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/okcoin/okcoin_websocket.go
  exchanges/okcoin/okcoin_ws_trade.go
  exchanges/stream/stream_match.go
  exchanges/stream/stream_match_test.go
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
Labels: review me

#1615 common/gateio/stream: add thread-safe counter and overide default GenerateMessageID with connection specific implementation
  common/common.go
  common/common_test.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/stream/stream_types.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_connection.go
  exchanges/stream/websocket_test.go
  exchanges/stream/websocket_types.go
Labels: bug, review me

#1626 okcoin: Remove exchange implementation
  README.md
  cmd/apichecker/apicheck.go
  cmd/apichecker/apicheck_test.go
  cmd/apichecker/testupdates.json
  cmd/apichecker/updates.json
  cmd/documentation/exchanges_templates/exchanges_trade_readme.tmpl
  cmd/documentation/exchanges_templates/okcoin.tmpl
  cmd/documentation/root_templates/root_readme.tmpl
  config/config.go
  config/config_test.go
  config_example.json
  docs/ADD_NEW_EXCHANGE.md
  docs/MULTICHAIN_TRANSFER_SUPPORT.md
  docs/OHLCV.md
  engine/helpers.go
  exchanges/okcoin/README.md
  exchanges/okcoin/okcoin.go
  exchanges/okcoin/okcoin_convert.go
  exchanges/okcoin/okcoin_errors_map.go
  exchanges/okcoin/okcoin_ratelimit.go
  exchanges/okcoin/okcoin_test.go
  exchanges/okcoin/okcoin_types.go
  exchanges/okcoin/okcoin_websocket.go
  exchanges/okcoin/okcoin_wrapper.go
  exchanges/okcoin/okcoin_ws_trade.go
  exchanges/order/order_types.go
  exchanges/support.go
  exchanges/trade/README.md
  portfolio/withdraw/withdraw_types.go
  testdata/configtest.json
  testdata/exchangelist.csv
Labels: review me

#1634 tests: Fix various issues
  .github/workflows/tests.yml
  backtester/eventhandlers/exchange/slippage/slippage_test.go
  common/file/file_test.go
  config/config_test.go
  exchanges/gateio/gateio.go
Labels: review me, test(s) fix

#1630 engine: Add overridable exchanges command line flag
  engine/engine.go
  engine/engine_test.go
  engine/engine_types.go
  main.go
Labels: review me
