Repository thrasher-corp/gocryptotrader, pull requests merged in 2024-04, with the labels that each got.

#1472 exchanges: shift GetDefaultConfig wrapper function to exchange.go
  backtester/engine/live.go
  backtester/engine/setup.go
  cmd/config_builder/builder.go
  cmd/exchange_template/wrapper_file.tmpl
  engine/engine_test.go
  engine/event_manager_test.go
  engine/helpers.go
  engine/order_manager_test.go
  engine/withdraw_manager_test.go
  exchanges/alphapoint/alphapoint_wrapper.go
  exchanges/binance/binance_wrapper.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bitflyer/bitflyer_wrapper.go
  exchanges/bithumb/bithumb_wrapper.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/bitstamp/bitstamp_wrapper.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/btse/btse_wrapper.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/coinut/coinut_wrapper.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/exmo/exmo_wrapper.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gemini/gemini_wrapper.go
  exchanges/hitbtc/hitbtc_wrapper.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/interfaces.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/lbank/lbank_wrapper.go
  exchanges/okcoin/okcoin_wrapper.go
  exchanges/okx/okx_wrapper.go
  exchanges/poloniex/poloniex_wrapper.go
  exchanges/sharedtestvalues/customex.go
  exchanges/yobit/yobit_wrapper.go
  gctscript/wrappers/gct/gctwrapper_test.go
Labels: low priority, review me, gcrc

#1506 request/nonce: simplify and prevent two consecutive mutex lock calls
  exchanges/alphapoint/alphapoint.go
  exchanges/bitfinex/bitfinex.go
  exchanges/bitstamp/bitstamp.go
  exchanges/exmo/exmo.go
  exchanges/gemini/gemini.go
  exchanges/kraken/kraken.go
  exchanges/nonce/nonce.go
  exchanges/nonce/nonce_test.go
  exchanges/poloniex/poloniex.go
  exchanges/request/request.go
  exchanges/request/request_test.go
  exchanges/yobit/yobit.go
Labels: low priority, review me, gcrc

#1509 Bithumb: Enhance testing coverage
  exchanges/bithumb/bithumb_test.go
Labels: review me, gcrc

#1505 Kraken: Fix wsCancelOrders not erroring with order id
  common/common.go
  common/common_test.go
  exchanges/binance/binance_test.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_websocket.go
  internal/testing/exchange/exchange.go
Labels: bug, review me, gcrc

#1522 Kraken: Fix GetLatestFundingRates requiring pair enabled
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  currency/manager.go
  currency/manager_test.go
  exchanges/kraken/kraken_wrapper.go
Labels: bug, review me, szrc, test(s) fix

#1524 gateio: fix spot/futures order issues
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/gateio_ws_futures.go
  exchanges/order/order_types.go
  exchanges/order/orders.go
Labels: bug, review me, high priority

#1526 qa: Enforce JSON linter for GCT configs
  .github/workflows/configs-json-lint.yml
  Makefile
  config_example.json
  testdata/configtest.json
Labels: review me
