Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-03, with the labels that each got.

#1823 bybit: support categorised channel
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_websocket.go
Labels: review me, gcrc, szrc

#1819 Poloniex: Fix GetChartData error return value
  exchanges/poloniex/poloniex.go
  exchanges/poloniex/poloniex_types.go
  exchanges/poloniex/poloniex_wrapper.go
Labels: bug, gcrc, szrc

#1825 Config: Tighten config version handling as uint16
  cmd/config/config.go
  config/config.go
  config/versions/versions.go
  config/versions/versions_test.go
Labels: bug, review me, gcrc, szrc

#1820 trade: remove exchangeName for AddTradesToBuffer
  exchanges/binance/binance_wrapper.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitfinex/bitfinex_websocket.go
  exchanges/bitstamp/bitstamp_websocket.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/btse/btse_websocket.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/coinbasepro/coinbasepro_websocket.go
  exchanges/coinut/coinut_websocket.go
  exchanges/deribit/deribit_websocket.go
  exchanges/exchange.go
  exchanges/gemini/gemini_websocket.go
  exchanges/hitbtc/hitbtc_websocket.go
  exchanges/huobi/huobi_websocket.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/stream/websocket.go
  exchanges/trade/trade.go
  exchanges/trade/trade_test.go
  exchanges/trade/trade_types.go
Labels: review me, gcrc, szrc

#1812 exchanges/margin: Fix marshalling issue
  exchanges/margin/margin.go
  exchanges/margin/margin_test.go
  exchanges/order/order_test.go
Labels: bug, review me, szrc

#1817 Huobi: Fix sending trades to the websocket DataHandler
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_websocket.go
  exchanges/huobi/testdata/wsAllTrades.json
  testdata/configtest.json
Labels: review me, gcrc, szrc

#1829 okx: move WsResponseMultiplexer to setDefaults
  exchanges/okx/okx_wrapper.go
Labels: review me, szrc

#1832 refactor: use t.TempDir() instead of os.MkdirTemp
  common/file/file_test.go
  exchanges/kline/kline_test.go
Labels: review me, szrc

#1827 exchanges/account: add UpdatedAt field to Balance and ProtectedBalance
  engine/rpcserver.go
  exchanges/account/account.go
  exchanges/account/account_test.go
  exchanges/account/account_types.go
  gctrpc/rpc.pb.go
  gctrpc/rpc.pb.gw.go
  gctrpc/rpc.proto
  gctrpc/rpc.swagger.json
  gctrpc/rpc_grpc.pb.go
Labels: review me, gcrc, szrc

#1828 binance: use types.Time instead of time.Time
  exchanges/binance/binance.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_types.go
  exchanges/binance/binance_ufutures.go
  exchanges/binance/binance_websocket.go
  exchanges/binance/binance_wrapper.go
  exchanges/binance/cfutures_types.go
  exchanges/binance/type_convert.go
  exchanges/binance/ufutures_types.go
Labels: review me, gcrc, szrc

#1833 Okx: Fix sending trades to the websocket DataHandler
  exchanges/okx/okx_test.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/testdata/wsAllTrades.json
  testdata/configtest.json
Labels: review me, gcrc, szrc

#1735 Config: AssetEnabled upgrade
  backtester/data/kline/api/api_test.go
  backtester/data/kline/live/live_test.go
  backtester/engine/backtest_test.go
  backtester/engine/live_test.go
  backtester/engine/setup.go
  backtester/eventhandlers/exchange/exchange_test.go
  backtester/funding/trackingcurrencies/trackingcurrencies_test.go
  cmd/exchange_template/wrapper_file.tmpl
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  config/config.go
  config/config_test.go
  config/versions/v4.go
  config/versions/v4_test.go
  config/versions/versions.go
  config/versions/versions_test.go
  currency/manager.go
  currency/manager_test.go
  currency/manager_types.go
  docs/ADD_NEW_EXCHANGE.md
  engine/datahistory_manager_test.go
  engine/helpers_test.go
  engine/order_manager_test.go
  engine/rpcserver_test.go
  exchanges/binance/binance_wrapper.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_wrapper.go
  exchanges/bitmex/bitmex_wrapper.go
  exchanges/btse/btse_wrapper.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/order/order_test.go
  exchanges/orderbook/simulator/simulator_test.go
  exchanges/sharedtestvalues/sharedtestvalues.go
  gctscript/wrappers/gct/gctwrapper_test.go
  testdata/configtest.json
Labels: review me, gcrc, szrc

#1737 Config: OrderManager upgrade
  backtester/engine/setup.go
  config/config.go
  config/config_types.go
  config/versions/v5.go
  config/versions/v5_test.go
  config/versions/versions.go
  engine/engine.go
  engine/order_manager.go
  engine/order_manager_test.go
  engine/order_manager_types.go
Labels: review me, gcrc, szrc

#1816 Okx: Various fixes including sonic
  .github/workflows/tests.yml
  CONTRIBUTORS
  Makefile
  README.md
  cmd/documentation/documentation.go
  cmd/documentation/root_templates/root_readme.tmpl
  encoding/json/common.go
  encoding/json/json.go
  encoding/json/sonic.go
  exchanges/okx/okx.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: bug, review me, szrc

#1845 BTSE: Fix sending trades to the websocket DataHandler
  exchanges/btse/btse_test.go
  exchanges/btse/btse_types.go
  exchanges/btse/btse_websocket.go
  exchanges/btse/testdata/wsAllTrades.json
  testdata/configtest.json
Labels: review me, gcrc, szrc

#1830 okx: optimize futures position orders retrieval
  exchanges/futures/contract.go
  exchanges/okx/okx_wrapper.go
Labels: review me, gcrc, szrc

#1847 BTC Markets: Fix sending trades to the websocket DataHandler
  exchanges/btcmarkets/btcmarkets_test.go
  exchanges/btcmarkets/btcmarkets_types.go
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/btcmarkets/testdata/wsAllTrades.json
  testdata/configtest.json
Labels: review me, gcrc, szrc

#1834 okx: fix type for AccountConfigurationResponse
  exchanges/okx/okx_types.go
  exchanges/okx/okx_wrapper.go
Labels: bug, review me, szrc

#1861 portfolio: Fix CryptoID balance issue and assertify tests
  cmd/portfolio/portfolio.go
  common/common.go
  common/common_test.go
  config/config_types.go
  config/versions/v5.go
  config/versions/v6.go
  config/versions/v6/types.go
  config/versions/v6_test.go
  config_example.json
  engine/engine.go
  engine/helpers.go
  engine/portfolio_manager.go
  portfolio/portfolio.go
  portfolio/portfolio_test.go
  portfolio/portfolio_types.go
  testdata/configtest.json
Labels: review me, test(s) fix

#1862 chore: fix some function names in comments
  cmd/apichecker/apicheck.go
  common/cache/lru.go
  currency/manager_test.go
  currency/pair_methods.go
Labels: review me
