Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-05, with the labels that each got.

#1896 GateIO: Fix regression of statusOpen
  exchanges/gateio/gateio_test.go
Labels: review me

#1886 exchanges/credentials: Improve handling and error reporting
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/coinbasepro/coinbasepro_websocket.go
  exchanges/credentials.go
  exchanges/credentials_test.go
  gctscript/wrappers/gct/gctwrapper_test.go
Labels: review me

#1875 account: add ProcessChange for balance update
  engine/websocketroutine_manager.go
  exchanges/account/account.go
  exchanges/account/account_test.go
  exchanges/account/account_types.go
  exchanges/bybit/bybit_websocket.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_websocket_futures.go
  exchanges/gateio/gateio_websocket_option.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_websocket.go
  exchanges/poloniex/poloniex_websocket.go
Labels: review me, gcrc, szrc

#1851 okx: Remove WsResponseMultiplexer and various refactors
  exchanges/okx/helpers.go
  exchanges/okx/okx.go
  exchanges/okx/okx_business_websocket.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/okx/ratelimit.go
  exchanges/okx/ratelimiter_test.go
  exchanges/okx/ws_requests.go
  exchanges/okx/ws_requests_test.go
Labels: bug, review me, high priority

#1901 Bitmex: Fix deprecated API endpoints and add config migration support
  config/versions/register.go
  config/versions/v8/v8.go
  config/versions/v8/v8_test.go
  exchanges/bitmex/bitmex_test.go
  exchanges/bitmex/bitmex_websocket.go
  exchanges/bitmex/bitmex_wrapper.go
Labels: bug, review me, szrc, test(s) fix

#1913 Deribit: Remove deprecated public and private portfolio margin endpoints
  exchanges/deribit/deribit.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_types.go
  exchanges/deribit/deribit_ws_endpoints.go
Labels: review me, szrc, test(s) fix

#1903 Huobi: Relax TestPairFromContractExpiryCode expiry date tests
  exchanges/huobi/huobi_test.go
Labels: szrc, test(s) fix

#1382 exchanges/order: Added TimeInForce type and values
  cmd/exchange_wrapper_issues/main.go
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
  engine/order_manager.go
  exchanges/binance/binance.go
  exchanges/binance/binance_cfutures.go
  exchanges/binance/binance_test.go
  exchanges/binance/binance_types.go
  exchanges/binance/binance_wrapper.go
  exchanges/binance/cfutures_types.go
  exchanges/binanceus/binanceus.go
  exchanges/binanceus/binanceus_test.go
  exchanges/binanceus/binanceus_types.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/btcmarkets/btcmarkets.go
  exchanges/btcmarkets/btcmarkets_test.go
  exchanges/btcmarkets/btcmarkets_wrapper.go
  exchanges/bybit/bybit_test.go
  exchanges/coinbasepro/coinbasepro.go
  exchanges/coinbasepro/coinbasepro_types.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/huobi/huobi_types.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/kraken/futures_types.go
  exchanges/kraken/kraken.go
  exchanges/kraken/kraken_futures.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_wrapper.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/okx/helpers.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_wrapper.go
  exchanges/order/limits_test.go
  exchanges/order/order_test.go
  exchanges/order/order_types.go
  exchanges/order/orders.go
  exchanges/order/timeinforce.go
  exchanges/order/timeinforce_test.go
  exchanges/poloniex/poloniex_wrapper.go
Labels: review me, szrc, medium priority

#1863 gateio: Fix websocket orderbook incremental updates
  exchange/websocket/buffer/buffer.go
  exchange/websocket/buffer/buffer_test.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_websocket_delivery_futures.go
  exchanges/gateio/gateio_websocket_futures.go
  exchanges/gateio/gateio_websocket_option.go
  exchanges/gateio/gateio_websocket_request_spot_test.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/ws_ob_update_manager.go
  exchanges/gateio/ws_ob_update_manager_test.go
  exchanges/kline/kline.go
  exchanges/kline/kline_test.go
  exchanges/kline/kline_types.go
  exchanges/orderbook/orderbook_types.go
  exchanges/subscription/fixtures_test.go
  exchanges/subscription/list.go
  exchanges/subscription/subscription.go
  exchanges/subscription/template.go
  exchanges/subscription/template_test.go
Labels: bug, review me, medium priority

#1919 exchanges: Fix race, improve error handling in ValidateKline and assertify related tests
  exchanges/exchange.go
  exchanges/exchange_test.go
Labels: test(s) fix

#1920 LBank: Fix TestGetWithdrawConfig, assertify tests and other minor changes
  exchanges/lbank/lbank.go
  exchanges/lbank/lbank_test.go
  exchanges/lbank/lbank_types.go
  exchanges/lbank/lbank_wrapper.go
  testdata/configtest.json
Labels: review me, test(s) fix
