Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-02, with the labels that each got.

#1420 exchanges: Okx Update
  common/common.go
  config_example.json
  database/repository/withdraw/withdraw.go
  database/repository/withdraw/withdraw_test.go
  exchanges/asset/asset.go
  exchanges/asset/asset_test.go
  exchanges/collateral/collateral.go
  exchanges/collateral/collateral_test.go
  exchanges/collateral/collateral_types.go
  exchanges/futures/contract.go
  exchanges/futures/contract_test.go
  exchanges/margin/margin.go
  exchanges/margin/margin_test.go
  exchanges/margin/margin_types.go
  exchanges/okx/helpers.go
  exchanges/okx/okx.go
  exchanges/okx/okx_business_websocket.go
  exchanges/okx/okx_err_codes.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_type_convert.go
  exchanges/okx/okx_types.go
  exchanges/okx/okx_websocket.go
  exchanges/okx/okx_wrapper.go
  exchanges/okx/ratelimit.go
  exchanges/okx/ratelimiter_test.go
  exchanges/order/order_test.go
  exchanges/order/order_types.go
  exchanges/order/orders.go
  testdata/configtest.json
Labels: review me, szrc, high priority

#1793 orderbook: fix fields not being retrieved when getting orderbook.Base
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
Labels: bug, review me, gcrc

#1681 stream/buffer: remove time.ticker publish limiter for websocket orderbook updates
  config/config.go
  config/config_types.go
  config/versions/v3.go
  config/versions/v3_test.go
  config_example.json
  exchanges/stream/buffer/buffer.go
  exchanges/stream/buffer/buffer_types.go
  testdata/configtest.json
Labels: review me, gcrc, medium priority

#1703 Huobi: V2 subscription support
  exchanges/huobi/cfutures_types.go
  exchanges/huobi/futures_types.go
  exchanges/huobi/huobi_test.go
  exchanges/huobi/huobi_types.go
  exchanges/huobi/huobi_websocket.go
  exchanges/huobi/huobi_wrapper.go
  exchanges/huobi/testdata/wsAllTrades.json
  exchanges/huobi/testdata/wsCandles.json
  exchanges/huobi/testdata/wsMyAccount.json
  exchanges/huobi/testdata/wsMyOrders.json
  exchanges/huobi/testdata/wsMyTrades.json
  exchanges/huobi/testdata/wsOrderbook.json
  exchanges/huobi/testdata/wsTicker.json
  exchanges/order/order_types.go
  exchanges/order/orders.go
  internal/testing/exchange/exchange.go
  testdata/configtest.json
Labels: review me, szrc

#1770 Config: Fix config version downgrade
  cmd/config/config.go
  config/config.go
  config/config_encryption.go
  config/config_encryption_test.go
  config/versions/versions.go
  config/versions/versions_test.go
Labels: bug, review me, gcrc, szrc

#1783 orderbook: Add methods for extracting associated details from depth
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
Labels: low priority, review me, gcrc

#1808 exchanges/btse: Handle TRUMPSOL in MarketPair.Pair and add test coverage
  exchanges/btse/btse_test.go
  exchanges/btse/btse_wrapper.go
Labels: review me, szrc, high priority, test(s) fix

#1717 stream: force subscription store check as stop gap for wrapper side implementation
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_websocket.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_websocket.go
  exchanges/stream/websocket.go
  exchanges/stream/websocket_test.go
  exchanges/subscription/store.go
  exchanges/subscription/store_test.go
Labels: bug, review me, gcrc
