Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-09, with the labels that each got.

#2022 web: Fix typo in settings component
  web/src/app/pages/settings/settings.component.html
Labels: review me

#1950 gateio: Fix contract market order validation and refactor related code
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket_request_futures.go
  exchanges/gateio/gateio_websocket_request_futures_test.go
  exchanges/gateio/gateio_wrapper.go
Labels: bug, review me

#2024 backtester/engine: Fix TestStart race
  backtester/engine/live_test.go
Labels: bug, review me

#2046 exchanges/refactor: Use strings.builder for string construction
  exchanges/btcmarkets/btcmarkets_websocket.go
  exchanges/bybit/bybit.go
Labels: review me, gcrc

#1672 bybit: Add websocket trading functionality across all assets
  engine/websocketroutine_manager.go
  exchange/websocket/connection.go
  exchange/websocket/connection_test.go
  exchange/websocket/manager.go
  exchange/websocket/manager_test.go
  exchange/websocket/subscriptions.go
  exchanges/bybit/bybit.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_websocket_requests.go
  exchanges/bybit/bybit_websocket_requests_test.go
  exchanges/bybit/bybit_websocket_requests_types.go
  exchanges/bybit/bybit_websocket_test.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/bybit/linear_websocket_test.go
  exchanges/bybit/options_websocket_test.go
  exchanges/bybit/order_arguments.go
  exchanges/bybit/order_arguments_test.go
  exchanges/bybit/ratelimit.go
  exchanges/bybit/ratelimit_test.go
  exchanges/bybit/spot_websocket.go
  exchanges/bybit/unmarshal.go
  exchanges/bybit/unmarshal_test.go
  exchanges/bybit/validate.go
  exchanges/bybit/validate_test.go
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/exchange_types.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/interfaces.go
  exchanges/order/order_test.go
  exchanges/order/orders.go
  exchanges/protocol/features.go
  exchanges/request/limit.go
  testdata/configtest.json
Labels: review me, gcrc, high priority

#2019 Binance/BinanceUS: Fix various live test failures
  exchanges/binance/binance.go
  exchanges/binance/binance_test.go
  exchanges/binance/testdata/http.json
  exchanges/binance/ufutures_types.go
  exchanges/binanceus/binanceus.go
  exchanges/binanceus/binanceus_test.go
  exchanges/binanceus/binanceus_types.go
  exchanges/binanceus/binanceus_wrapper.go
Labels: review me, gcrc, test(s) fix
