Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-06, with the labels that each got.

#1899 exchanges: Types and Unmarshaling methods update
  exchanges/binanceus/binanceus.go
  exchanges/binanceus/binanceus_test.go
  exchanges/binanceus/binanceus_types.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/binanceus/binanceus_wrapper.go
  exchanges/binanceus/type_convert.go
  exchanges/bybit/bybit_test.go
  exchanges/coinbasepro/coinbasepro.go
  exchanges/coinbasepro/coinbasepro_test.go
  exchanges/coinbasepro/coinbasepro_types.go
  exchanges/coinbasepro/coinbasepro_wrapper.go
  exchanges/deribit/deribit.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_types.go
  exchanges/deribit/deribit_ws_endpoints.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/kucoin/kucoin.go
  exchanges/kucoin/kucoin_futures.go
  exchanges/kucoin/kucoin_futures_types.go
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_types.go
  exchanges/kucoin/kucoin_wrapper.go
  exchanges/okx/okx_test.go
  exchanges/okx/okx_types.go
  exchanges/order/timeinforce_test.go
Labels: review me, szrc, medium priority

#1929 config: Fix TestPromptForConfigEncryption race
  config/config.go
  config/config_encryption.go
  config/config_encryption_test.go
Labels: review me, szrc, test(s) fix

#1936 types/time, exchanges/kraken: Refactor spot/futures time types
  exchanges/kraken/futures_types.go
  exchanges/kraken/kraken_test.go
  exchanges/kraken/kraken_types.go
  exchanges/kraken/kraken_websocket.go
  exchanges/kraken/kraken_wrapper.go
  types/time.go
  types/time_test.go
Labels: bug, review me

#1917 exchanges: Rename `UpdatePushedAt` field to `LastPushed` use field in gateio REST books
  exchange/websocket/buffer/buffer.go
  exchanges/bybit/bybit_websocket.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_websocket_futures.go
  exchanges/gateio/gateio_websocket_option.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/gateio/ws_ob_update_manager_test.go
  exchanges/orderbook/depth.go
  exchanges/orderbook/depth_test.go
  exchanges/orderbook/orderbook.go
  exchanges/orderbook/orderbook_types.go
Labels: review me

#1938 chore: fix some function names in comment
  currency/storage.go
  exchanges/bybit/bybit_wrapper.go
Labels: review me, szrc

#1939 Bitmex: Use mock server for leaderboard and historical stats tests
  exchanges/bitmex/bitmex_test.go
  exchanges/bitmex/bitmex_types.go
Labels: review me, szrc, test(s) fix
