Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-04, with the labels that each got.

#1865 Bitfinex: Fix intermittent TestGenerateSubscriptions and ticker FRRAmountAvailable failures
  exchanges/bitfinex/bitfinex.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitfinex/bitfinex_types.go
Labels: review me, szrc, test(s) fix

#1866 Huobi: Fix TestPairFromContractExpiryCode on CW
  exchanges/huobi/huobi_test.go
Labels: review me, szrc, test(s) fix

#1867 Config: Eliminate shared config version package vars
  config/versions/v2.go
  config/versions/v4.go
  config/versions/v4_test.go
  config/versions/v5.go
  config/versions/v5/defaults.go
  config/versions/v5_test.go
  config/versions/v6_test.go
  config/versions/versions.go
Labels: review me, gcrc, szrc

#1846 account: refactor for save holdings
  common/key/key.go
  engine/rpcserver.go
  exchanges/account/account.go
  exchanges/account/account_test.go
  exchanges/account/account_types.go
Labels: review me, szrc, test(s) fix

#1856 Deribit: Fix sending trades to the websocket DataHandler
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_types.go
  exchanges/deribit/deribit_websocket.go
  exchanges/deribit/testdata/wsAllTrades.json
Labels: review me, gcrc, szrc

#1884 Kucoin: Fix failing TestSubscribeBatchLimit
  exchanges/kucoin/kucoin_test.go
Labels: szrc, test(s) fix

#1791 deribit: Update FetchTradablePairs to not need a currency code
  exchanges/deribit/deribit.go
  exchanges/deribit/deribit_test.go
  exchanges/deribit/deribit_wrapper.go
  exchanges/deribit/deribit_ws_endpoints.go
Labels: review me, gcrc

#1885 cmd/documentation: Add pagination support for contributors
  CONTRIBUTORS
  README.md
  cmd/documentation/documentation.go
  cmd/documentation/documentation_test.go
  engine/currency_state_manager.md
Labels: low priority, review me, szrc

#1890 OKX: Relax TestGetLeadTraderCurrentLeadPositions
  exchanges/okx/okx_test.go
Labels: review me, test(s) fix

#1887 Config: Refactor version packages
  config/versions/register.go
  config/versions/register_test.go
  config/versions/v0.go
  config/versions/v0/v0.go
  config/versions/v0/v0_test.go
  config/versions/v1/v1.go
  config/versions/v1/v1_test.go
  config/versions/v2/v2.go
  config/versions/v2/v2_test.go
  config/versions/v3/v3.go
  config/versions/v3/v3_test.go
  config/versions/v4/v4.go
  config/versions/v4/v4_test.go
  config/versions/v5/v5.go
  config/versions/v5/v5_test.go
  config/versions/v6/v6.go
  config/versions/v6/v6_test.go
  config/versions/versions.go
  config/versions/versions_test.go
Labels: review me, gcrc, szrc

#1889 gateio: add ConvertSmallBalances, GetAccountDetails and GetUserTransactionRateLimitInfo methods
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/ratelimiter.go
Labels: review me

#1882 Exchanges: Remove WalletAddress
  cmd/exchange_wrapper_issues/main.go
  cmd/exchange_wrapper_issues/types.go
  cmd/gctcli/commands.go
  engine/rpcserver.go
  exchanges/alphapoint/alphapoint_test.go
  exchanges/binance/binance_test.go
  exchanges/bitfinex/bitfinex_test.go
  exchanges/bitflyer/bitflyer_test.go
  exchanges/bithumb/bithumb_test.go
  exchanges/bitmex/bitmex_test.go
  exchanges/btse/btse_test.go
  exchanges/coinbasepro/coinbasepro_test.go
  exchanges/coinut/coinut_test.go
  exchanges/deribit/deribit_test.go
  exchanges/exmo/exmo_test.go
  exchanges/gemini/gemini_test.go
  exchanges/hitbtc/hitbtc_test.go
  exchanges/huobi/huobi_test.go
  exchanges/kucoin/kucoin_test.go
  exchanges/okx/okx_test.go
  exchanges/order/order_test.go
  exchanges/order/order_types.go
  exchanges/order/orders.go
  exchanges/poloniex/poloniex_test.go
  exchanges/yobit/yobit_test.go
  gctrpc/rpc.pb.go
  gctrpc/rpc.pb.gw.go
  gctrpc/rpc.proto
  gctrpc/rpc.swagger.json
Labels: review me, gcrc, szrc
