Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-08, with the labels that each got.

#1974 workflows: Add check for common LLM targeted unicode characters
  .github/workflows/misc.yml
  backtester/eventhandlers/portfolio/portfolio_test.go
  exchanges/bybit/bybit.go
Labels: review me

#1670 bybit: enable multiconnection handling across websocket endpoints
  common/common.go
  common/common_test.go
  docs/ADD_NEW_EXCHANGE.md
  exchange/websocket/connection.go
  exchange/websocket/manager.go
  exchange/websocket/manager_test.go
  exchanges/bybit/bybit.go
  exchanges/bybit/bybit_inverse_websocket.go
  exchanges/bybit/bybit_linear_websocket.go
  exchanges/bybit/bybit_options_websocket.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_websocket.go
  exchanges/bybit/bybit_wrapper.go
  exchanges/bybit/inverse_websocket.go
  exchanges/bybit/inverse_websocket_test.go
  exchanges/bybit/linear_websocket.go
  exchanges/bybit/linear_websocket_test.go
  exchanges/bybit/options_websocket.go
  exchanges/bybit/options_websocket_test.go
  exchanges/bybit/spot_websocket.go
  exchanges/bybit/spot_websocket_test.go
  exchanges/bybit/testdata/wsAuth.json
  exchanges/exchange.go
  exchanges/exchange_test.go
  exchanges/exchange_types.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_websocket_request_spot.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/okx/okx_wrapper.go
Labels: review me, high priority

#1969 Bithumb: Filter zero quantity values in GetOrderBook
  exchanges/bithumb/bithumb.go
  exchanges/bithumb/bithumb_test.go
  exchanges/bithumb/bithumb_types.go
Labels: review me, test(s) fix

#1982 cmd/exchange_wrapper_standards: Fix race on t.Context in exchange wrapper tests
  cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go
Labels: review me, test(s) fix

#2012 linters: Add modernise tool check and fix issues
  .github/workflows/config-versions-lint.yml
  .github/workflows/configs-json-lint.yml
  .github/workflows/misc.yml
  Makefile
  backtester/engine/backtest.go
  backtester/engine/backtest_test.go
  backtester/engine/live_test.go
  cmd/exchange_wrapper_coverage/main.go
  cmd/exchange_wrapper_issues/main.go
  docs/CODING_GUIDELINES.md
  engine/apiserver.go
  engine/engine.go
  engine/websocketroutine_manager.go
  exchange/websocket/connection.go
  exchanges/binance/binance_websocket.go
  exchanges/binanceus/binanceus_websocket.go
  exchanges/bithumb/bithumb_ws_orderbook.go
  exchanges/gateio/gateio_websocket_request_types.go
  exchanges/kucoin/kucoin_futures.go
  exchanges/kucoin/kucoin_websocket.go
  exchanges/orderbook/orderbook_test.go
  exchanges/ticker/ticker_test.go
Labels: review me

#2020 devcontainer: Update Dockerfile and settings for VSCode
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/post_create.sh
Labels: review me
