Repository thrasher-corp/gocryptotrader, pull requests merged in 2025-01, with the labels that each got.

#1739 bybit: Add protected subtype for account checking to reduce outbound requests
  exchanges/bybit/bybit.go
  exchanges/bybit/bybit_live_test.go
  exchanges/bybit/bybit_test.go
  exchanges/bybit/bybit_types.go
  exchanges/bybit/bybit_wrapper.go
Labels: review me, gcrc

#1689 CI/GHA: Add stale activity action for issues and PRs
  .github/workflows/stale.yml
Labels: blocked

#1765 Subscriptions: Fix IBotExchange not implementing sub.IExchange
  exchanges/interfaces.go
  exchanges/subscription/interface_test.go
  exchanges/subscription/list.go
  exchanges/subscription/template.go
Labels: bug, review me, gcrc, szrc

#1761 Kucoin: Margin subscription fix and improvements
  README.md
  cmd/documentation/exchanges_templates/kucoin.tmpl
  engine/currency_state_manager.md
  exchanges/kucoin/README.md
  exchanges/kucoin/kucoin_test.go
  exchanges/kucoin/kucoin_websocket.go
Labels: bug, review me, gcrc, szrc

#1766 GateIO: Fix GetFuturesContractDetails for Deliveries and minor other fixes
  .golangci.yml
  currency/pairs.go
  engine/rpcserver.go
  exchanges/btse/btse_wrapper.go
  exchanges/gateio/gateio.go
  exchanges/gateio/gateio_test.go
  exchanges/gateio/gateio_types.go
  exchanges/gateio/gateio_websocket.go
  exchanges/gateio/gateio_websocket_futures.go
  exchanges/gateio/gateio_websocket_option.go
  exchanges/gateio/gateio_wrapper.go
  exchanges/subscription/template.go
Labels: bug, review me, gcrc, szrc

#1782 Binance: Add order side
  exchanges/binance/binance_types.go
  exchanges/binance/binance_websocket.go
  exchanges/binance/binance_wrapper.go
Labels: review me

#1790 Codespell: Fix failures with 2.4.0
  .codespellrc
  .github/workflows/spell-checker.yml
  backtester/engine/grpcserver.go
  contrib/spellcheck/exclude_lines.txt
  contrib/spellcheck/ignore_words.txt
  exchanges/gateio/gateio_types.go
  exchanges/request/request.go
Labels: review me, test(s) fix
